package com.plateform.service;

import com.plateform.entity.Trans;

import java.util.List;

public interface TransService {

    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_tech
     *
     * @mbg.generated Sun Sep 29 19:13:57 CST 2019
     */
    int insert(Trans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_tech
     *
     * @mbg.generated Sun Sep 29 19:13:57 CST 2019
     */
    Trans selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_tech
     *
     * @mbg.generated Sun Sep 29 19:13:57 CST 2019
     */
    List<Trans> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_tech
     *
     * @mbg.generated Sun Sep 29 19:13:57 CST 2019
     */
    int updateByPrimaryKey(Trans record);


    int updateMemberStatusByMemberNo(String memberNo,String memberStatus);


    List<Trans> selectByTransObjid(String transObjid);
    List<Trans> selectByApplicantNo(String applicantNo);

    int updateByExampleSelective(Trans record);
}