package com.plateform.entity;



public class Admin {


    private Integer id;
    private String adminNo;
    private String adminName;
    private String permissionLevel;
    private String adminDescribe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column admin.ID
     *
     * @return the value of admin.ID
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column admin.ID
     *
     * @param id the value for admin.ID
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column admin.ADMIN_NO
     *
     * @return the value of admin.ADMIN_NO
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getAdminNo() {
        return adminNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column admin.ADMIN_NO
     *
     * @param adminNo the value for admin.ADMIN_NO
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setAdminNo(String adminNo) {
        this.adminNo = adminNo == null ? null : adminNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column admin.ADMIN_NAME
     *
     * @return the value of admin.ADMIN_NAME
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column admin.ADMIN_NAME
     *
     * @param adminName the value for admin.ADMIN_NAME
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column admin.PERMISSION_LEVEL
     *
     * @return the value of admin.PERMISSION_LEVEL
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getPermissionLevel() {
        return permissionLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column admin.PERMISSION_LEVEL
     *
     * @param permissionLevel the value for admin.PERMISSION_LEVEL
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setPermissionLevel(String permissionLevel) {
        this.permissionLevel = permissionLevel == null ? null : permissionLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column admin.ADMIN_DESCRIBE
     *
     * @return the value of admin.ADMIN_DESCRIBE
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getAdminDescribe() {
        return adminDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column admin.ADMIN_DESCRIBE
     *
     * @param adminDescribe the value for admin.ADMIN_DESCRIBE
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setAdminDescribe(String adminDescribe) {
        this.adminDescribe = adminDescribe == null ? null : adminDescribe.trim();
    }
}