package com.plateform.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class  Advice {
    private Integer id;
    private String adviceNo;
    private String memberNo;
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    private Date adviceTime;
    private String adviceContent;
    private String handler;
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    private Date handleTime;
    private String handleResult;
    private String detail;
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column advice.ID
     *
     * @return the value of advice.ID
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column advice.ID
     *
     * @param id the value for advice.ID
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column advice.ADVICE_NO
     *
     * @return the value of advice.ADVICE_NO
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getAdviceNo() {
        return adviceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column advice.ADVICE_NO
     *
     * @param adviceNo the value for advice.ADVICE_NO
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setAdviceNo(String adviceNo) {
        this.adviceNo = adviceNo == null ? null : adviceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column advice.MEMBER_NO
     *
     * @return the value of advice.MEMBER_NO
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getMemberNo() {
        return memberNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column advice.MEMBER_NO
     *
     * @param memberNo the value for advice.MEMBER_NO
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setMemberNo(String memberNo) {
        this.memberNo = memberNo == null ? null : memberNo.trim();
    }


    public Date getAdviceTime() {
        return adviceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column advice.ADVICE_TIME
     *
     * @param adviceTime the value for advice.ADVICE_TIME
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setAdviceTime(Date adviceTime) {
        this.adviceTime = adviceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column advice.ADVICE_CONTENT
     *
     * @return the value of advice.ADVICE_CONTENT
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getAdviceContent() {
        return adviceContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column advice.ADVICE_CONTENT
     *
     * @param adviceContent the value for advice.ADVICE_CONTENT
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setAdviceContent(String adviceContent) {
        this.adviceContent = adviceContent == null ? null : adviceContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column advice.HANDLER
     *
     * @return the value of advice.HANDLER
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getHandler() {
        return handler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column advice.HANDLER
     *
     * @param handler the value for advice.HANDLER
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setHandler(String handler) {
        this.handler = handler == null ? null : handler.trim();
    }


    public Date getHandleTime() {
        return handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column advice.HANDLE_TIME
     *
     * @param handleTime the value for advice.HANDLE_TIME
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setHandleTime(Date handleTime) {
        this.handleTime = handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column advice.HANDLE_RESULT
     *
     * @return the value of advice.HANDLE_RESULT
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getHandleResult() {
        return handleResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column advice.HANDLE_RESULT
     *
     * @param handleResult the value for advice.HANDLE_RESULT
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setHandleResult(String handleResult) {
        this.handleResult = handleResult == null ? null : handleResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column advice.DETAIL
     *
     * @return the value of advice.DETAIL
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column advice.DETAIL
     *
     * @param detail the value for advice.DETAIL
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column advice.REMARK
     *
     * @return the value of advice.REMARK
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column advice.REMARK
     *
     * @param remark the value for advice.REMARK
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}