package com.plateform.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Bid {

    private Integer id;
    private String bidNo;
    private String memberNo;
    private String biddocNo;
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    private Date bidTime;
    private String bidContent;
    private String status;
    private String bidResult;
    private String handler;
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column bid.ID
     *
     * @return the value of bid.ID
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column bid.ID
     *
     * @param id the value for bid.ID
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column bid.BID_NO
     *
     * @return the value of bid.BID_NO
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getBidNo() {
        return bidNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column bid.BID_NO
     *
     * @param bidNo the value for bid.BID_NO
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setBidNo(String bidNo) {
        this.bidNo = bidNo == null ? null : bidNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column bid.MEMBER_NO
     *
     * @return the value of bid.MEMBER_NO
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getMemberNo() {
        return memberNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column bid.MEMBER_NO
     *
     * @param memberNo the value for bid.MEMBER_NO
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setMemberNo(String memberNo) {
        this.memberNo = memberNo == null ? null : memberNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column bid.BIDDOC_NO
     *
     * @return the value of bid.BIDDOC_NO
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getBiddocNo() {
        return biddocNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column bid.BIDDOC_NO
     *
     * @param biddocNo the value for bid.BIDDOC_NO
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setBiddocNo(String biddocNo) {
        this.biddocNo = biddocNo == null ? null : biddocNo.trim();
    }

    public Date getBidTime() {
        return bidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column bid.BID_TIME
     *
     * @param bidTime the value for bid.BID_TIME
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setBidTime(Date bidTime) {
        this.bidTime = bidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column bid.BID_CONTENT
     *
     * @return the value of bid.BID_CONTENT
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getBidContent() {
        return bidContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column bid.BID_CONTENT
     *
     * @param bidContent the value for bid.BID_CONTENT
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setBidContent(String bidContent) {
        this.bidContent = bidContent == null ? null : bidContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column bid.STATUS
     *
     * @return the value of bid.STATUS
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column bid.STATUS
     *
     * @param status the value for bid.STATUS
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column bid.BID_RESULT
     *
     * @return the value of bid.BID_RESULT
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getBidResult() {
        return bidResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column bid.BID_RESULT
     *
     * @param bidResult the value for bid.BID_RESULT
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setBidResult(String bidResult) {
        this.bidResult = bidResult == null ? null : bidResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column bid.HANDLER
     *
     * @return the value of bid.HANDLER
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getHandler() {
        return handler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column bid.HANDLER
     *
     * @param handler the value for bid.HANDLER
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setHandler(String handler) {
        this.handler = handler == null ? null : handler.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column bid.DETAIL
     *
     * @return the value of bid.DETAIL
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column bid.DETAIL
     *
     * @param detail the value for bid.DETAIL
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }
}