package com.plateform.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Hres implements EncodableEntity {

    private Integer id;
    private String abilityNo;
    private String memberNo;
    private String abilityDescription;
    private String humanResource;
    private String facilityResource;
    private String envResource;
    private String softResource;
    private String otherResource;
    private String sharingCondition;
    private String costEstimate;
    private String remark;
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    private Date joinTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column hres.ID
     *
     * @return the value of hres.ID
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column hres.ID
     *
     * @param id the value for hres.ID
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column hres.ABILITY_NO
     *
     * @return the value of hres.ABILITY_NO
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public String getAbilityNo() {
        return abilityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column hres.ABILITY_NO
     *
     * @param abilityNo the value for hres.ABILITY_NO
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setAbilityNo(String abilityNo) {
        this.abilityNo = abilityNo == null ? null : abilityNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column hres.MEMBER_NO
     *
     * @return the value of hres.MEMBER_NO
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public String getMemberNo() {
        return memberNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column hres.MEMBER_NO
     *
     * @param memberNo the value for hres.MEMBER_NO
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setMemberNo(String memberNo) {
        this.memberNo = memberNo == null ? null : memberNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column hres.ABILITY_DESCRIPTION
     *
     * @return the value of hres.ABILITY_DESCRIPTION
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public String getAbilityDescription() {
        return abilityDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column hres.ABILITY_DESCRIPTION
     *
     * @param abilityDescription the value for hres.ABILITY_DESCRIPTION
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setAbilityDescription(String abilityDescription) {
        this.abilityDescription = abilityDescription == null ? null : abilityDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column hres.HUMAN_RESOURCE
     *
     * @return the value of hres.HUMAN_RESOURCE
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public String getHumanResource() {
        return humanResource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column hres.HUMAN_RESOURCE
     *
     * @param humanResource the value for hres.HUMAN_RESOURCE
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setHumanResource(String humanResource) {
        this.humanResource = humanResource == null ? null : humanResource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column hres.FACILITY_RESOURCE
     *
     * @return the value of hres.FACILITY_RESOURCE
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public String getFacilityResource() {
        return facilityResource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column hres.FACILITY_RESOURCE
     *
     * @param facilityResource the value for hres.FACILITY_RESOURCE
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setFacilityResource(String facilityResource) {
        this.facilityResource = facilityResource == null ? null : facilityResource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column hres.ENV_RESOURCE
     *
     * @return the value of hres.ENV_RESOURCE
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public String getEnvResource() {
        return envResource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column hres.ENV_RESOURCE
     *
     * @param envResource the value for hres.ENV_RESOURCE
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setEnvResource(String envResource) {
        this.envResource = envResource == null ? null : envResource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column hres.SOFT_RESOURCE
     *
     * @return the value of hres.SOFT_RESOURCE
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public String getSoftResource() {
        return softResource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column hres.SOFT_RESOURCE
     *
     * @param softResource the value for hres.SOFT_RESOURCE
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setSoftResource(String softResource) {
        this.softResource = softResource == null ? null : softResource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column hres.OTHER_RESOURCE
     *
     * @return the value of hres.OTHER_RESOURCE
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public String getOtherResource() {
        return otherResource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column hres.OTHER_RESOURCE
     *
     * @param otherResource the value for hres.OTHER_RESOURCE
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setOtherResource(String otherResource) {
        this.otherResource = otherResource == null ? null : otherResource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column hres.SHARING_CONDITION
     *
     * @return the value of hres.SHARING_CONDITION
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public String getSharingCondition() {
        return sharingCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column hres.SHARING_CONDITION
     *
     * @param sharingCondition the value for hres.SHARING_CONDITION
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setSharingCondition(String sharingCondition) {
        this.sharingCondition = sharingCondition == null ? null : sharingCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column hres.COST_ESTIMATE
     *
     * @return the value of hres.COST_ESTIMATE
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public String getCostEstimate() {
        return costEstimate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column hres.COST_ESTIMATE
     *
     * @param costEstimate the value for hres.COST_ESTIMATE
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setCostEstimate(String costEstimate) {
        this.costEstimate = costEstimate == null ? null : costEstimate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column hres.REMARK
     *
     * @return the value of hres.REMARK
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column hres.REMARK
     *
     * @param remark the value for hres.REMARK
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column hres.JOIN_TIME
     *
     * @return the value of hres.JOIN_TIME
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
    public Date getJoinTime() {
        return joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column hres.JOIN_TIME
     *
     * @param joinTime the value for hres.JOIN_TIME
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setJoinTime(Date joinTime) {
        this.joinTime = joinTime;
    }
}