package com.plateform.entity;

public class Login {

    private Integer id;
    private String loginuser;
    private String name;
    private String password;
    private String role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column login.ID
     *
     * @return the value of login.ID
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column login.ID
     *
     * @param id the value for login.ID
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column login.LOGINUSER
     *
     * @return the value of login.LOGINUSER
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public String getLoginuser() {
        return loginuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column login.LOGINUSER
     *
     * @param loginuser the value for login.LOGINUSER
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setLoginuser(String loginuser) {
        this.loginuser = loginuser == null ? null : loginuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column login.NAME
     *
     * @return the value of login.NAME
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column login.NAME
     *
     * @param name the value for login.NAME
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column login.PASSWORD
     *
     * @return the value of login.PASSWORD
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column login.PASSWORD
     *
     * @param password the value for login.PASSWORD
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column login.ROLE
     *
     * @return the value of login.ROLE
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column login.ROLE
     *
     * @param role the value for login.ROLE
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }
}