package com.plateform.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.plateform.service.implement.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.util.Date;
import java.util.List;

@Component
public class Member {

    private Integer id;
    private String memberNo;
    private String memberName;
    private String memberAbbr;
    private String memberRegisterAddr;
    private String memberAddr;
    private String corporation;
    private String topManager;
    private String contact;
    private String contactInformation;
    private String unitProperty;
    private String industry;
    private String businessArea;
    private String businessExpire;
    private String captial;
    private String staffCount;
    private String productValue;
    private String remark;
    private String resDesc;
    private String abilityDesc;
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    private Date joinTime;
    private Integer serviceTime;
    private Integer serviceSuccessTime;
    private String protocolUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_member.ID
     *
     * @return the value of spt_member.ID
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_member.ID
     *
     * @param id the value for spt_member.ID
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_member.MEMBER_NO
     *
     * @return the value of spt_member.MEMBER_NO
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public String getMemberNo() {
        return memberNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_member.MEMBER_NO
     *
     * @param memberNo the value for spt_member.MEMBER_NO
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public void setMemberNo(String memberNo) {
        this.memberNo = memberNo == null ? null : memberNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_member.MEMBER_NAME
     *
     * @return the value of spt_member.MEMBER_NAME
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_member.MEMBER_NAME
     *
     * @param memberName the value for spt_member.MEMBER_NAME
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_member.MEMBER_ABBR
     *
     * @return the value of spt_member.MEMBER_ABBR
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public String getMemberAbbr() {
        return memberAbbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_member.MEMBER_ABBR
     *
     * @param memberAbbr the value for spt_member.MEMBER_ABBR
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public void setMemberAbbr(String memberAbbr) {
        this.memberAbbr = memberAbbr == null ? null : memberAbbr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_member.MEMBER_REGISTER_ADDR
     *
     * @return the value of spt_member.MEMBER_REGISTER_ADDR
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public String getMemberRegisterAddr() {
        return memberRegisterAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_member.MEMBER_REGISTER_ADDR
     *
     * @param memberRegisterAddr the value for spt_member.MEMBER_REGISTER_ADDR
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public void setMemberRegisterAddr(String memberRegisterAddr) {
        this.memberRegisterAddr = memberRegisterAddr == null ? null : memberRegisterAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_member.MEMBER_ADDR
     *
     * @return the value of spt_member.MEMBER_ADDR
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public String getMemberAddr() {
        return memberAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_member.MEMBER_ADDR
     *
     * @param memberAddr the value for spt_member.MEMBER_ADDR
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public void setMemberAddr(String memberAddr) {
        this.memberAddr = memberAddr == null ? null : memberAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_member.CORPORATION
     *
     * @return the value of spt_member.CORPORATION
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public String getCorporation() {
        return corporation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_member.CORPORATION
     *
     * @param corporation the value for spt_member.CORPORATION
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public void setCorporation(String corporation) {
        this.corporation = corporation == null ? null : corporation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_member.TOP_MANAGER
     *
     * @return the value of spt_member.TOP_MANAGER
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public String getTopManager() {
        return topManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_member.TOP_MANAGER
     *
     * @param topManager the value for spt_member.TOP_MANAGER
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public void setTopManager(String topManager) {
        this.topManager = topManager == null ? null : topManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_member.CONTACT
     *
     * @return the value of spt_member.CONTACT
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_member.CONTACT
     *
     * @param contact the value for spt_member.CONTACT
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_member.CONTACT_INFORMATION
     *
     * @return the value of spt_member.CONTACT_INFORMATION
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public String getContactInformation() {
        return contactInformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_member.CONTACT_INFORMATION
     *
     * @param contactInformation the value for spt_member.CONTACT_INFORMATION
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public void setContactInformation(String contactInformation) {
        this.contactInformation = contactInformation == null ? null : contactInformation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_member.UNIT_PROPERTY
     *
     * @return the value of spt_member.UNIT_PROPERTY
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public String getUnitProperty() {
        return unitProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_member.UNIT_PROPERTY
     *
     * @param unitProperty the value for spt_member.UNIT_PROPERTY
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public void setUnitProperty(String unitProperty) {
        this.unitProperty = unitProperty == null ? null : unitProperty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_member.INDUSTRY
     *
     * @return the value of spt_member.INDUSTRY
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_member.INDUSTRY
     *
     * @param industry the value for spt_member.INDUSTRY
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_member.BUSINESS_AREA
     *
     * @return the value of spt_member.BUSINESS_AREA
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public String getBusinessArea() {
        return businessArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_member.BUSINESS_AREA
     *
     * @param businessArea the value for spt_member.BUSINESS_AREA
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public void setBusinessArea(String businessArea) {
        this.businessArea = businessArea == null ? null : businessArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_member.BUSINESS_EXPIRE
     *
     * @return the value of spt_member.BUSINESS_EXPIRE
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public String getBusinessExpire() {
        return businessExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_member.BUSINESS_EXPIRE
     *
     * @param businessExpire the value for spt_member.BUSINESS_EXPIRE
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public void setBusinessExpire(String businessExpire) {
        this.businessExpire = businessExpire == null ? null : businessExpire.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_member.CAPTIAL
     *
     * @return the value of spt_member.CAPTIAL
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public String getCaptial() {
        return captial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_member.CAPTIAL
     *
     * @param captial the value for spt_member.CAPTIAL
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public void setCaptial(String captial) {
        this.captial = captial == null ? null : captial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_member.STAFF_COUNT
     *
     * @return the value of spt_member.STAFF_COUNT
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public String getStaffCount() {
        return staffCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_member.STAFF_COUNT
     *
     * @param staffCount the value for spt_member.STAFF_COUNT
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public void setStaffCount(String staffCount) {
        this.staffCount = staffCount == null ? null : staffCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_member.PRODUCT_VALUE
     *
     * @return the value of spt_member.PRODUCT_VALUE
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public String getProductValue() {
        return productValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_member.PRODUCT_VALUE
     *
     * @param productValue the value for spt_member.PRODUCT_VALUE
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public void setProductValue(String productValue) {
        this.productValue = productValue == null ? null : productValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_member.REMARK
     *
     * @return the value of spt_member.REMARK
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_member.REMARK
     *
     * @param remark the value for spt_member.REMARK
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_member.RES_DESC
     *
     * @return the value of spt_member.RES_DESC
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public String getResDesc() {
        return resDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_member.RES_DESC
     *
     * @param resDesc the value for spt_member.RES_DESC
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public void setResDesc(String resDesc) {
        this.resDesc = resDesc == null ? null : resDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_member.ABILITY_DESC
     *
     * @return the value of spt_member.ABILITY_DESC
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public String getAbilityDesc() {
        return abilityDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_member.ABILITY_DESC
     *
     * @param abilityDesc the value for spt_member.ABILITY_DESC
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public void setAbilityDesc(String abilityDesc) {
        this.abilityDesc = abilityDesc == null ? null : abilityDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_member.JOIN_TIME
     *
     * @return the value of spt_member.JOIN_TIME
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public Date getJoinTime() {
        return joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_member.JOIN_TIME
     *
     * @param joinTime the value for spt_member.JOIN_TIME
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public void setJoinTime(Date joinTime) {
        this.joinTime = joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_member.SERVICE_TIME
     *
     * @return the value of spt_member.SERVICE_TIME
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public Integer getServiceTime() {
        return serviceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_member.SERVICE_TIME
     *
     * @param serviceTime the value for spt_member.SERVICE_TIME
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public void setServiceTime(Integer serviceTime) {
        this.serviceTime = serviceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_member.SERVICE_SUCCESS_TIME
     *
     * @return the value of spt_member.SERVICE_SUCCESS_TIME
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public Integer getServiceSuccessTime() {
        return serviceSuccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_member.SERVICE_SUCCESS_TIME
     *
     * @param serviceSuccessTime the value for spt_member.SERVICE_SUCCESS_TIME
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public void setServiceSuccessTime(Integer serviceSuccessTime) {
        this.serviceSuccessTime = serviceSuccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_member.PROTOCOL_URL
     *
     * @return the value of spt_member.PROTOCOL_URL
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public String getProtocolUrl() {
        return protocolUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_member.PROTOCOL_URL
     *
     * @param protocolUrl the value for spt_member.PROTOCOL_URL
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public void setProtocolUrl(String protocolUrl) {
        this.protocolUrl = protocolUrl == null ? null : protocolUrl.trim();
    }


        //@Override
        //public String toString() {
        //    return "Member{" +
        //            "id=" + id +
        //            ", memberNo='" + memberNo + '\'' +
        //            ", memberName='" + memberName + '\'' +
        //            ", memberAddr='" + memberAddr + '\'' +
        //            ", memberPhone='" + memberPhone + '\'' +
        //            ", memberMail='" + memberMail + '\'' +
        //            ", memberEmail='" + memberEmail + '\'' +
        //            ", contact='" + contact + '\'' +
        //            ", contactPhone='" + contactPhone + '\'' +
        //            ", unitProperty='" + unitProperty + '\'' +
        //            ", industry='" + industry + '\'' +
        //            ", joinTime=" + joinTime +
        //            ", serviceTime=" + serviceTime +
        //            ", serviceSuccessTime=" + serviceSuccessTime +
        //            ", protocolUrl='" + protocolUrl + '\'' +
        //            '}';
        //}

        //public Member() {
        //    this.id = null;
        //    this.memberNo="%";
        //    this.memberName="%";
        //    this.memberAddr="%";
        //    this.memberPhone="%";
        //    this.memberMail="%";
        //    this.memberEmail="%";
        //    this.contact="%";
        //    this.contactPhone="%";
        //    this.unitProperty="%";
        //    this.industry="%";
        //    this.joinTime=new Date();
        //    this.serviceTime=0;
        //    this.serviceSuccessTime=0;
        //    this.protocolUrl="%";
        //}

        private static LoginServiceImpl loginService;
        private static TempMemberServiceImpl tempMemberService;
        private static TempMemberPictureImpl tempMemberPicture;

        @Autowired
        public void setLoginService(LoginServiceImpl loginService) {
            Member.loginService = loginService;
        }

        @Autowired
        public void setTempMemberService(TempMemberServiceImpl tempMemberService) {
            Member.tempMemberService = tempMemberService;
        }

        @Autowired
        public void setSavePicture(TempMemberPictureImpl tempMemberPicture) {
            Member.tempMemberPicture = tempMemberPicture;
        }

        //获得注册状态
        public static int getRegisterStage(String name){
            List<Login> loginResult = loginService.selectByName(name);
            if (loginService.selectByName(name).isEmpty())
            {
                return 0;
            }

            //检查该用户的角色属性
            if (!loginResult.get(0).getRole().equals("tempMember"))
            {
                return -1;
            }

            //当该用户没有编号时，判断为阶段1
            String userId = loginResult.get(0).getLoginuser();
            if (null == userId || 0 == userId.length())
            {
                return 1;
            }


            //当该用户有编号但是在spp_member表中没有查询到该用户的详细信息时，判断为阶段1
            List<Member> infoResult = tempMemberService.selectByMemberNo(userId);
            if (infoResult.isEmpty())
            {
                return 1;
            }

            //当该用户有详细信息但没有上传相关证件则返回阶段2
            if (tempMemberPicture.selectPicture(userId, "1") == null ||
                    tempMemberPicture.selectPicture(userId,"2") == null ||
                    tempMemberPicture.selectPicture(userId,"3") == null) {
                return 2;
            }

            //都能查询到时，用户处于各种资料都完备的状态，返回阶段3
            return 3;
        }
}