package com.plateform.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class MemberExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the trash table spt_member
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the trash table spt_member
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the trash table spt_member
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spt_member
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public MemberExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spt_member
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spt_member
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spt_member
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spt_member
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spt_member
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spt_member
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spt_member
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spt_member
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spt_member
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spt_member
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the trash table spt_member
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMemberNoIsNull() {
            addCriterion("MEMBER_NO is null");
            return (Criteria) this;
        }

        public Criteria andMemberNoIsNotNull() {
            addCriterion("MEMBER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andMemberNoEqualTo(String value) {
            addCriterion("MEMBER_NO =", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoNotEqualTo(String value) {
            addCriterion("MEMBER_NO <>", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoGreaterThan(String value) {
            addCriterion("MEMBER_NO >", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoGreaterThanOrEqualTo(String value) {
            addCriterion("MEMBER_NO >=", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoLessThan(String value) {
            addCriterion("MEMBER_NO <", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoLessThanOrEqualTo(String value) {
            addCriterion("MEMBER_NO <=", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoLike(String value) {
            addCriterion("MEMBER_NO like", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoNotLike(String value) {
            addCriterion("MEMBER_NO not like", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoIn(List<String> values) {
            addCriterion("MEMBER_NO in", values, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoNotIn(List<String> values) {
            addCriterion("MEMBER_NO not in", values, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoBetween(String value1, String value2) {
            addCriterion("MEMBER_NO between", value1, value2, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoNotBetween(String value1, String value2) {
            addCriterion("MEMBER_NO not between", value1, value2, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNameIsNull() {
            addCriterion("MEMBER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andMemberNameIsNotNull() {
            addCriterion("MEMBER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andMemberNameEqualTo(String value) {
            addCriterion("MEMBER_NAME =", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameNotEqualTo(String value) {
            addCriterion("MEMBER_NAME <>", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameGreaterThan(String value) {
            addCriterion("MEMBER_NAME >", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameGreaterThanOrEqualTo(String value) {
            addCriterion("MEMBER_NAME >=", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameLessThan(String value) {
            addCriterion("MEMBER_NAME <", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameLessThanOrEqualTo(String value) {
            addCriterion("MEMBER_NAME <=", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameLike(String value) {
            addCriterion("MEMBER_NAME like", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameNotLike(String value) {
            addCriterion("MEMBER_NAME not like", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameIn(List<String> values) {
            addCriterion("MEMBER_NAME in", values, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameNotIn(List<String> values) {
            addCriterion("MEMBER_NAME not in", values, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameBetween(String value1, String value2) {
            addCriterion("MEMBER_NAME between", value1, value2, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameNotBetween(String value1, String value2) {
            addCriterion("MEMBER_NAME not between", value1, value2, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberAbbrIsNull() {
            addCriterion("MEMBER_ABBR is null");
            return (Criteria) this;
        }

        public Criteria andMemberAbbrIsNotNull() {
            addCriterion("MEMBER_ABBR is not null");
            return (Criteria) this;
        }

        public Criteria andMemberAbbrEqualTo(String value) {
            addCriterion("MEMBER_ABBR =", value, "memberAbbr");
            return (Criteria) this;
        }

        public Criteria andMemberAbbrNotEqualTo(String value) {
            addCriterion("MEMBER_ABBR <>", value, "memberAbbr");
            return (Criteria) this;
        }

        public Criteria andMemberAbbrGreaterThan(String value) {
            addCriterion("MEMBER_ABBR >", value, "memberAbbr");
            return (Criteria) this;
        }

        public Criteria andMemberAbbrGreaterThanOrEqualTo(String value) {
            addCriterion("MEMBER_ABBR >=", value, "memberAbbr");
            return (Criteria) this;
        }

        public Criteria andMemberAbbrLessThan(String value) {
            addCriterion("MEMBER_ABBR <", value, "memberAbbr");
            return (Criteria) this;
        }

        public Criteria andMemberAbbrLessThanOrEqualTo(String value) {
            addCriterion("MEMBER_ABBR <=", value, "memberAbbr");
            return (Criteria) this;
        }

        public Criteria andMemberAbbrLike(String value) {
            addCriterion("MEMBER_ABBR like", value, "memberAbbr");
            return (Criteria) this;
        }

        public Criteria andMemberAbbrNotLike(String value) {
            addCriterion("MEMBER_ABBR not like", value, "memberAbbr");
            return (Criteria) this;
        }

        public Criteria andMemberAbbrIn(List<String> values) {
            addCriterion("MEMBER_ABBR in", values, "memberAbbr");
            return (Criteria) this;
        }

        public Criteria andMemberAbbrNotIn(List<String> values) {
            addCriterion("MEMBER_ABBR not in", values, "memberAbbr");
            return (Criteria) this;
        }

        public Criteria andMemberAbbrBetween(String value1, String value2) {
            addCriterion("MEMBER_ABBR between", value1, value2, "memberAbbr");
            return (Criteria) this;
        }

        public Criteria andMemberAbbrNotBetween(String value1, String value2) {
            addCriterion("MEMBER_ABBR not between", value1, value2, "memberAbbr");
            return (Criteria) this;
        }

        public Criteria andMemberRegisterAddrIsNull() {
            addCriterion("MEMBER_REGISTER_ADDR is null");
            return (Criteria) this;
        }

        public Criteria andMemberRegisterAddrIsNotNull() {
            addCriterion("MEMBER_REGISTER_ADDR is not null");
            return (Criteria) this;
        }

        public Criteria andMemberRegisterAddrEqualTo(String value) {
            addCriterion("MEMBER_REGISTER_ADDR =", value, "memberRegisterAddr");
            return (Criteria) this;
        }

        public Criteria andMemberRegisterAddrNotEqualTo(String value) {
            addCriterion("MEMBER_REGISTER_ADDR <>", value, "memberRegisterAddr");
            return (Criteria) this;
        }

        public Criteria andMemberRegisterAddrGreaterThan(String value) {
            addCriterion("MEMBER_REGISTER_ADDR >", value, "memberRegisterAddr");
            return (Criteria) this;
        }

        public Criteria andMemberRegisterAddrGreaterThanOrEqualTo(String value) {
            addCriterion("MEMBER_REGISTER_ADDR >=", value, "memberRegisterAddr");
            return (Criteria) this;
        }

        public Criteria andMemberRegisterAddrLessThan(String value) {
            addCriterion("MEMBER_REGISTER_ADDR <", value, "memberRegisterAddr");
            return (Criteria) this;
        }

        public Criteria andMemberRegisterAddrLessThanOrEqualTo(String value) {
            addCriterion("MEMBER_REGISTER_ADDR <=", value, "memberRegisterAddr");
            return (Criteria) this;
        }

        public Criteria andMemberRegisterAddrLike(String value) {
            addCriterion("MEMBER_REGISTER_ADDR like", value, "memberRegisterAddr");
            return (Criteria) this;
        }

        public Criteria andMemberRegisterAddrNotLike(String value) {
            addCriterion("MEMBER_REGISTER_ADDR not like", value, "memberRegisterAddr");
            return (Criteria) this;
        }

        public Criteria andMemberRegisterAddrIn(List<String> values) {
            addCriterion("MEMBER_REGISTER_ADDR in", values, "memberRegisterAddr");
            return (Criteria) this;
        }

        public Criteria andMemberRegisterAddrNotIn(List<String> values) {
            addCriterion("MEMBER_REGISTER_ADDR not in", values, "memberRegisterAddr");
            return (Criteria) this;
        }

        public Criteria andMemberRegisterAddrBetween(String value1, String value2) {
            addCriterion("MEMBER_REGISTER_ADDR between", value1, value2, "memberRegisterAddr");
            return (Criteria) this;
        }

        public Criteria andMemberRegisterAddrNotBetween(String value1, String value2) {
            addCriterion("MEMBER_REGISTER_ADDR not between", value1, value2, "memberRegisterAddr");
            return (Criteria) this;
        }

        public Criteria andMemberAddrIsNull() {
            addCriterion("MEMBER_ADDR is null");
            return (Criteria) this;
        }

        public Criteria andMemberAddrIsNotNull() {
            addCriterion("MEMBER_ADDR is not null");
            return (Criteria) this;
        }

        public Criteria andMemberAddrEqualTo(String value) {
            addCriterion("MEMBER_ADDR =", value, "memberAddr");
            return (Criteria) this;
        }

        public Criteria andMemberAddrNotEqualTo(String value) {
            addCriterion("MEMBER_ADDR <>", value, "memberAddr");
            return (Criteria) this;
        }

        public Criteria andMemberAddrGreaterThan(String value) {
            addCriterion("MEMBER_ADDR >", value, "memberAddr");
            return (Criteria) this;
        }

        public Criteria andMemberAddrGreaterThanOrEqualTo(String value) {
            addCriterion("MEMBER_ADDR >=", value, "memberAddr");
            return (Criteria) this;
        }

        public Criteria andMemberAddrLessThan(String value) {
            addCriterion("MEMBER_ADDR <", value, "memberAddr");
            return (Criteria) this;
        }

        public Criteria andMemberAddrLessThanOrEqualTo(String value) {
            addCriterion("MEMBER_ADDR <=", value, "memberAddr");
            return (Criteria) this;
        }

        public Criteria andMemberAddrLike(String value) {
            addCriterion("MEMBER_ADDR like", value, "memberAddr");
            return (Criteria) this;
        }

        public Criteria andMemberAddrNotLike(String value) {
            addCriterion("MEMBER_ADDR not like", value, "memberAddr");
            return (Criteria) this;
        }

        public Criteria andMemberAddrIn(List<String> values) {
            addCriterion("MEMBER_ADDR in", values, "memberAddr");
            return (Criteria) this;
        }

        public Criteria andMemberAddrNotIn(List<String> values) {
            addCriterion("MEMBER_ADDR not in", values, "memberAddr");
            return (Criteria) this;
        }

        public Criteria andMemberAddrBetween(String value1, String value2) {
            addCriterion("MEMBER_ADDR between", value1, value2, "memberAddr");
            return (Criteria) this;
        }

        public Criteria andMemberAddrNotBetween(String value1, String value2) {
            addCriterion("MEMBER_ADDR not between", value1, value2, "memberAddr");
            return (Criteria) this;
        }

        public Criteria andCorporationIsNull() {
            addCriterion("CORPORATION is null");
            return (Criteria) this;
        }

        public Criteria andCorporationIsNotNull() {
            addCriterion("CORPORATION is not null");
            return (Criteria) this;
        }

        public Criteria andCorporationEqualTo(String value) {
            addCriterion("CORPORATION =", value, "corporation");
            return (Criteria) this;
        }

        public Criteria andCorporationNotEqualTo(String value) {
            addCriterion("CORPORATION <>", value, "corporation");
            return (Criteria) this;
        }

        public Criteria andCorporationGreaterThan(String value) {
            addCriterion("CORPORATION >", value, "corporation");
            return (Criteria) this;
        }

        public Criteria andCorporationGreaterThanOrEqualTo(String value) {
            addCriterion("CORPORATION >=", value, "corporation");
            return (Criteria) this;
        }

        public Criteria andCorporationLessThan(String value) {
            addCriterion("CORPORATION <", value, "corporation");
            return (Criteria) this;
        }

        public Criteria andCorporationLessThanOrEqualTo(String value) {
            addCriterion("CORPORATION <=", value, "corporation");
            return (Criteria) this;
        }

        public Criteria andCorporationLike(String value) {
            addCriterion("CORPORATION like", value, "corporation");
            return (Criteria) this;
        }

        public Criteria andCorporationNotLike(String value) {
            addCriterion("CORPORATION not like", value, "corporation");
            return (Criteria) this;
        }

        public Criteria andCorporationIn(List<String> values) {
            addCriterion("CORPORATION in", values, "corporation");
            return (Criteria) this;
        }

        public Criteria andCorporationNotIn(List<String> values) {
            addCriterion("CORPORATION not in", values, "corporation");
            return (Criteria) this;
        }

        public Criteria andCorporationBetween(String value1, String value2) {
            addCriterion("CORPORATION between", value1, value2, "corporation");
            return (Criteria) this;
        }

        public Criteria andCorporationNotBetween(String value1, String value2) {
            addCriterion("CORPORATION not between", value1, value2, "corporation");
            return (Criteria) this;
        }

        public Criteria andTopManagerIsNull() {
            addCriterion("TOP_MANAGER is null");
            return (Criteria) this;
        }

        public Criteria andTopManagerIsNotNull() {
            addCriterion("TOP_MANAGER is not null");
            return (Criteria) this;
        }

        public Criteria andTopManagerEqualTo(String value) {
            addCriterion("TOP_MANAGER =", value, "topManager");
            return (Criteria) this;
        }

        public Criteria andTopManagerNotEqualTo(String value) {
            addCriterion("TOP_MANAGER <>", value, "topManager");
            return (Criteria) this;
        }

        public Criteria andTopManagerGreaterThan(String value) {
            addCriterion("TOP_MANAGER >", value, "topManager");
            return (Criteria) this;
        }

        public Criteria andTopManagerGreaterThanOrEqualTo(String value) {
            addCriterion("TOP_MANAGER >=", value, "topManager");
            return (Criteria) this;
        }

        public Criteria andTopManagerLessThan(String value) {
            addCriterion("TOP_MANAGER <", value, "topManager");
            return (Criteria) this;
        }

        public Criteria andTopManagerLessThanOrEqualTo(String value) {
            addCriterion("TOP_MANAGER <=", value, "topManager");
            return (Criteria) this;
        }

        public Criteria andTopManagerLike(String value) {
            addCriterion("TOP_MANAGER like", value, "topManager");
            return (Criteria) this;
        }

        public Criteria andTopManagerNotLike(String value) {
            addCriterion("TOP_MANAGER not like", value, "topManager");
            return (Criteria) this;
        }

        public Criteria andTopManagerIn(List<String> values) {
            addCriterion("TOP_MANAGER in", values, "topManager");
            return (Criteria) this;
        }

        public Criteria andTopManagerNotIn(List<String> values) {
            addCriterion("TOP_MANAGER not in", values, "topManager");
            return (Criteria) this;
        }

        public Criteria andTopManagerBetween(String value1, String value2) {
            addCriterion("TOP_MANAGER between", value1, value2, "topManager");
            return (Criteria) this;
        }

        public Criteria andTopManagerNotBetween(String value1, String value2) {
            addCriterion("TOP_MANAGER not between", value1, value2, "topManager");
            return (Criteria) this;
        }

        public Criteria andContactIsNull() {
            addCriterion("CONTACT is null");
            return (Criteria) this;
        }

        public Criteria andContactIsNotNull() {
            addCriterion("CONTACT is not null");
            return (Criteria) this;
        }

        public Criteria andContactEqualTo(String value) {
            addCriterion("CONTACT =", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactNotEqualTo(String value) {
            addCriterion("CONTACT <>", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactGreaterThan(String value) {
            addCriterion("CONTACT >", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactGreaterThanOrEqualTo(String value) {
            addCriterion("CONTACT >=", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactLessThan(String value) {
            addCriterion("CONTACT <", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactLessThanOrEqualTo(String value) {
            addCriterion("CONTACT <=", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactLike(String value) {
            addCriterion("CONTACT like", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactNotLike(String value) {
            addCriterion("CONTACT not like", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactIn(List<String> values) {
            addCriterion("CONTACT in", values, "contact");
            return (Criteria) this;
        }

        public Criteria andContactNotIn(List<String> values) {
            addCriterion("CONTACT not in", values, "contact");
            return (Criteria) this;
        }

        public Criteria andContactBetween(String value1, String value2) {
            addCriterion("CONTACT between", value1, value2, "contact");
            return (Criteria) this;
        }

        public Criteria andContactNotBetween(String value1, String value2) {
            addCriterion("CONTACT not between", value1, value2, "contact");
            return (Criteria) this;
        }

        public Criteria andContactInformationIsNull() {
            addCriterion("CONTACT_INFORMATION is null");
            return (Criteria) this;
        }

        public Criteria andContactInformationIsNotNull() {
            addCriterion("CONTACT_INFORMATION is not null");
            return (Criteria) this;
        }

        public Criteria andContactInformationEqualTo(String value) {
            addCriterion("CONTACT_INFORMATION =", value, "contactInformation");
            return (Criteria) this;
        }

        public Criteria andContactInformationNotEqualTo(String value) {
            addCriterion("CONTACT_INFORMATION <>", value, "contactInformation");
            return (Criteria) this;
        }

        public Criteria andContactInformationGreaterThan(String value) {
            addCriterion("CONTACT_INFORMATION >", value, "contactInformation");
            return (Criteria) this;
        }

        public Criteria andContactInformationGreaterThanOrEqualTo(String value) {
            addCriterion("CONTACT_INFORMATION >=", value, "contactInformation");
            return (Criteria) this;
        }

        public Criteria andContactInformationLessThan(String value) {
            addCriterion("CONTACT_INFORMATION <", value, "contactInformation");
            return (Criteria) this;
        }

        public Criteria andContactInformationLessThanOrEqualTo(String value) {
            addCriterion("CONTACT_INFORMATION <=", value, "contactInformation");
            return (Criteria) this;
        }

        public Criteria andContactInformationLike(String value) {
            addCriterion("CONTACT_INFORMATION like", value, "contactInformation");
            return (Criteria) this;
        }

        public Criteria andContactInformationNotLike(String value) {
            addCriterion("CONTACT_INFORMATION not like", value, "contactInformation");
            return (Criteria) this;
        }

        public Criteria andContactInformationIn(List<String> values) {
            addCriterion("CONTACT_INFORMATION in", values, "contactInformation");
            return (Criteria) this;
        }

        public Criteria andContactInformationNotIn(List<String> values) {
            addCriterion("CONTACT_INFORMATION not in", values, "contactInformation");
            return (Criteria) this;
        }

        public Criteria andContactInformationBetween(String value1, String value2) {
            addCriterion("CONTACT_INFORMATION between", value1, value2, "contactInformation");
            return (Criteria) this;
        }

        public Criteria andContactInformationNotBetween(String value1, String value2) {
            addCriterion("CONTACT_INFORMATION not between", value1, value2, "contactInformation");
            return (Criteria) this;
        }

        public Criteria andUnitPropertyIsNull() {
            addCriterion("UNIT_PROPERTY is null");
            return (Criteria) this;
        }

        public Criteria andUnitPropertyIsNotNull() {
            addCriterion("UNIT_PROPERTY is not null");
            return (Criteria) this;
        }

        public Criteria andUnitPropertyEqualTo(String value) {
            addCriterion("UNIT_PROPERTY =", value, "unitProperty");
            return (Criteria) this;
        }

        public Criteria andUnitPropertyNotEqualTo(String value) {
            addCriterion("UNIT_PROPERTY <>", value, "unitProperty");
            return (Criteria) this;
        }

        public Criteria andUnitPropertyGreaterThan(String value) {
            addCriterion("UNIT_PROPERTY >", value, "unitProperty");
            return (Criteria) this;
        }

        public Criteria andUnitPropertyGreaterThanOrEqualTo(String value) {
            addCriterion("UNIT_PROPERTY >=", value, "unitProperty");
            return (Criteria) this;
        }

        public Criteria andUnitPropertyLessThan(String value) {
            addCriterion("UNIT_PROPERTY <", value, "unitProperty");
            return (Criteria) this;
        }

        public Criteria andUnitPropertyLessThanOrEqualTo(String value) {
            addCriterion("UNIT_PROPERTY <=", value, "unitProperty");
            return (Criteria) this;
        }

        public Criteria andUnitPropertyLike(String value) {
            addCriterion("UNIT_PROPERTY like", value, "unitProperty");
            return (Criteria) this;
        }

        public Criteria andUnitPropertyNotLike(String value) {
            addCriterion("UNIT_PROPERTY not like", value, "unitProperty");
            return (Criteria) this;
        }

        public Criteria andUnitPropertyIn(List<String> values) {
            addCriterion("UNIT_PROPERTY in", values, "unitProperty");
            return (Criteria) this;
        }

        public Criteria andUnitPropertyNotIn(List<String> values) {
            addCriterion("UNIT_PROPERTY not in", values, "unitProperty");
            return (Criteria) this;
        }

        public Criteria andUnitPropertyBetween(String value1, String value2) {
            addCriterion("UNIT_PROPERTY between", value1, value2, "unitProperty");
            return (Criteria) this;
        }

        public Criteria andUnitPropertyNotBetween(String value1, String value2) {
            addCriterion("UNIT_PROPERTY not between", value1, value2, "unitProperty");
            return (Criteria) this;
        }

        public Criteria andIndustryIsNull() {
            addCriterion("INDUSTRY is null");
            return (Criteria) this;
        }

        public Criteria andIndustryIsNotNull() {
            addCriterion("INDUSTRY is not null");
            return (Criteria) this;
        }

        public Criteria andIndustryEqualTo(String value) {
            addCriterion("INDUSTRY =", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryNotEqualTo(String value) {
            addCriterion("INDUSTRY <>", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryGreaterThan(String value) {
            addCriterion("INDUSTRY >", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryGreaterThanOrEqualTo(String value) {
            addCriterion("INDUSTRY >=", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryLessThan(String value) {
            addCriterion("INDUSTRY <", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryLessThanOrEqualTo(String value) {
            addCriterion("INDUSTRY <=", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryLike(String value) {
            addCriterion("INDUSTRY like", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryNotLike(String value) {
            addCriterion("INDUSTRY not like", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryIn(List<String> values) {
            addCriterion("INDUSTRY in", values, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryNotIn(List<String> values) {
            addCriterion("INDUSTRY not in", values, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryBetween(String value1, String value2) {
            addCriterion("INDUSTRY between", value1, value2, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryNotBetween(String value1, String value2) {
            addCriterion("INDUSTRY not between", value1, value2, "industry");
            return (Criteria) this;
        }

        public Criteria andBusinessAreaIsNull() {
            addCriterion("BUSINESS_AREA is null");
            return (Criteria) this;
        }

        public Criteria andBusinessAreaIsNotNull() {
            addCriterion("BUSINESS_AREA is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessAreaEqualTo(String value) {
            addCriterion("BUSINESS_AREA =", value, "businessArea");
            return (Criteria) this;
        }

        public Criteria andBusinessAreaNotEqualTo(String value) {
            addCriterion("BUSINESS_AREA <>", value, "businessArea");
            return (Criteria) this;
        }

        public Criteria andBusinessAreaGreaterThan(String value) {
            addCriterion("BUSINESS_AREA >", value, "businessArea");
            return (Criteria) this;
        }

        public Criteria andBusinessAreaGreaterThanOrEqualTo(String value) {
            addCriterion("BUSINESS_AREA >=", value, "businessArea");
            return (Criteria) this;
        }

        public Criteria andBusinessAreaLessThan(String value) {
            addCriterion("BUSINESS_AREA <", value, "businessArea");
            return (Criteria) this;
        }

        public Criteria andBusinessAreaLessThanOrEqualTo(String value) {
            addCriterion("BUSINESS_AREA <=", value, "businessArea");
            return (Criteria) this;
        }

        public Criteria andBusinessAreaLike(String value) {
            addCriterion("BUSINESS_AREA like", value, "businessArea");
            return (Criteria) this;
        }

        public Criteria andBusinessAreaNotLike(String value) {
            addCriterion("BUSINESS_AREA not like", value, "businessArea");
            return (Criteria) this;
        }

        public Criteria andBusinessAreaIn(List<String> values) {
            addCriterion("BUSINESS_AREA in", values, "businessArea");
            return (Criteria) this;
        }

        public Criteria andBusinessAreaNotIn(List<String> values) {
            addCriterion("BUSINESS_AREA not in", values, "businessArea");
            return (Criteria) this;
        }

        public Criteria andBusinessAreaBetween(String value1, String value2) {
            addCriterion("BUSINESS_AREA between", value1, value2, "businessArea");
            return (Criteria) this;
        }

        public Criteria andBusinessAreaNotBetween(String value1, String value2) {
            addCriterion("BUSINESS_AREA not between", value1, value2, "businessArea");
            return (Criteria) this;
        }

        public Criteria andBusinessExpireIsNull() {
            addCriterion("BUSINESS_EXPIRE is null");
            return (Criteria) this;
        }

        public Criteria andBusinessExpireIsNotNull() {
            addCriterion("BUSINESS_EXPIRE is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessExpireEqualTo(String value) {
            addCriterion("BUSINESS_EXPIRE =", value, "businessExpire");
            return (Criteria) this;
        }

        public Criteria andBusinessExpireNotEqualTo(String value) {
            addCriterion("BUSINESS_EXPIRE <>", value, "businessExpire");
            return (Criteria) this;
        }

        public Criteria andBusinessExpireGreaterThan(String value) {
            addCriterion("BUSINESS_EXPIRE >", value, "businessExpire");
            return (Criteria) this;
        }

        public Criteria andBusinessExpireGreaterThanOrEqualTo(String value) {
            addCriterion("BUSINESS_EXPIRE >=", value, "businessExpire");
            return (Criteria) this;
        }

        public Criteria andBusinessExpireLessThan(String value) {
            addCriterion("BUSINESS_EXPIRE <", value, "businessExpire");
            return (Criteria) this;
        }

        public Criteria andBusinessExpireLessThanOrEqualTo(String value) {
            addCriterion("BUSINESS_EXPIRE <=", value, "businessExpire");
            return (Criteria) this;
        }

        public Criteria andBusinessExpireLike(String value) {
            addCriterion("BUSINESS_EXPIRE like", value, "businessExpire");
            return (Criteria) this;
        }

        public Criteria andBusinessExpireNotLike(String value) {
            addCriterion("BUSINESS_EXPIRE not like", value, "businessExpire");
            return (Criteria) this;
        }

        public Criteria andBusinessExpireIn(List<String> values) {
            addCriterion("BUSINESS_EXPIRE in", values, "businessExpire");
            return (Criteria) this;
        }

        public Criteria andBusinessExpireNotIn(List<String> values) {
            addCriterion("BUSINESS_EXPIRE not in", values, "businessExpire");
            return (Criteria) this;
        }

        public Criteria andBusinessExpireBetween(String value1, String value2) {
            addCriterion("BUSINESS_EXPIRE between", value1, value2, "businessExpire");
            return (Criteria) this;
        }

        public Criteria andBusinessExpireNotBetween(String value1, String value2) {
            addCriterion("BUSINESS_EXPIRE not between", value1, value2, "businessExpire");
            return (Criteria) this;
        }

        public Criteria andCaptialIsNull() {
            addCriterion("CAPTIAL is null");
            return (Criteria) this;
        }

        public Criteria andCaptialIsNotNull() {
            addCriterion("CAPTIAL is not null");
            return (Criteria) this;
        }

        public Criteria andCaptialEqualTo(String value) {
            addCriterion("CAPTIAL =", value, "captial");
            return (Criteria) this;
        }

        public Criteria andCaptialNotEqualTo(String value) {
            addCriterion("CAPTIAL <>", value, "captial");
            return (Criteria) this;
        }

        public Criteria andCaptialGreaterThan(String value) {
            addCriterion("CAPTIAL >", value, "captial");
            return (Criteria) this;
        }

        public Criteria andCaptialGreaterThanOrEqualTo(String value) {
            addCriterion("CAPTIAL >=", value, "captial");
            return (Criteria) this;
        }

        public Criteria andCaptialLessThan(String value) {
            addCriterion("CAPTIAL <", value, "captial");
            return (Criteria) this;
        }

        public Criteria andCaptialLessThanOrEqualTo(String value) {
            addCriterion("CAPTIAL <=", value, "captial");
            return (Criteria) this;
        }

        public Criteria andCaptialLike(String value) {
            addCriterion("CAPTIAL like", value, "captial");
            return (Criteria) this;
        }

        public Criteria andCaptialNotLike(String value) {
            addCriterion("CAPTIAL not like", value, "captial");
            return (Criteria) this;
        }

        public Criteria andCaptialIn(List<String> values) {
            addCriterion("CAPTIAL in", values, "captial");
            return (Criteria) this;
        }

        public Criteria andCaptialNotIn(List<String> values) {
            addCriterion("CAPTIAL not in", values, "captial");
            return (Criteria) this;
        }

        public Criteria andCaptialBetween(String value1, String value2) {
            addCriterion("CAPTIAL between", value1, value2, "captial");
            return (Criteria) this;
        }

        public Criteria andCaptialNotBetween(String value1, String value2) {
            addCriterion("CAPTIAL not between", value1, value2, "captial");
            return (Criteria) this;
        }

        public Criteria andStaffCountIsNull() {
            addCriterion("STAFF_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andStaffCountIsNotNull() {
            addCriterion("STAFF_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andStaffCountEqualTo(String value) {
            addCriterion("STAFF_COUNT =", value, "staffCount");
            return (Criteria) this;
        }

        public Criteria andStaffCountNotEqualTo(String value) {
            addCriterion("STAFF_COUNT <>", value, "staffCount");
            return (Criteria) this;
        }

        public Criteria andStaffCountGreaterThan(String value) {
            addCriterion("STAFF_COUNT >", value, "staffCount");
            return (Criteria) this;
        }

        public Criteria andStaffCountGreaterThanOrEqualTo(String value) {
            addCriterion("STAFF_COUNT >=", value, "staffCount");
            return (Criteria) this;
        }

        public Criteria andStaffCountLessThan(String value) {
            addCriterion("STAFF_COUNT <", value, "staffCount");
            return (Criteria) this;
        }

        public Criteria andStaffCountLessThanOrEqualTo(String value) {
            addCriterion("STAFF_COUNT <=", value, "staffCount");
            return (Criteria) this;
        }

        public Criteria andStaffCountLike(String value) {
            addCriterion("STAFF_COUNT like", value, "staffCount");
            return (Criteria) this;
        }

        public Criteria andStaffCountNotLike(String value) {
            addCriterion("STAFF_COUNT not like", value, "staffCount");
            return (Criteria) this;
        }

        public Criteria andStaffCountIn(List<String> values) {
            addCriterion("STAFF_COUNT in", values, "staffCount");
            return (Criteria) this;
        }

        public Criteria andStaffCountNotIn(List<String> values) {
            addCriterion("STAFF_COUNT not in", values, "staffCount");
            return (Criteria) this;
        }

        public Criteria andStaffCountBetween(String value1, String value2) {
            addCriterion("STAFF_COUNT between", value1, value2, "staffCount");
            return (Criteria) this;
        }

        public Criteria andStaffCountNotBetween(String value1, String value2) {
            addCriterion("STAFF_COUNT not between", value1, value2, "staffCount");
            return (Criteria) this;
        }

        public Criteria andProductValueIsNull() {
            addCriterion("PRODUCT_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andProductValueIsNotNull() {
            addCriterion("PRODUCT_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andProductValueEqualTo(String value) {
            addCriterion("PRODUCT_VALUE =", value, "productValue");
            return (Criteria) this;
        }

        public Criteria andProductValueNotEqualTo(String value) {
            addCriterion("PRODUCT_VALUE <>", value, "productValue");
            return (Criteria) this;
        }

        public Criteria andProductValueGreaterThan(String value) {
            addCriterion("PRODUCT_VALUE >", value, "productValue");
            return (Criteria) this;
        }

        public Criteria andProductValueGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCT_VALUE >=", value, "productValue");
            return (Criteria) this;
        }

        public Criteria andProductValueLessThan(String value) {
            addCriterion("PRODUCT_VALUE <", value, "productValue");
            return (Criteria) this;
        }

        public Criteria andProductValueLessThanOrEqualTo(String value) {
            addCriterion("PRODUCT_VALUE <=", value, "productValue");
            return (Criteria) this;
        }

        public Criteria andProductValueLike(String value) {
            addCriterion("PRODUCT_VALUE like", value, "productValue");
            return (Criteria) this;
        }

        public Criteria andProductValueNotLike(String value) {
            addCriterion("PRODUCT_VALUE not like", value, "productValue");
            return (Criteria) this;
        }

        public Criteria andProductValueIn(List<String> values) {
            addCriterion("PRODUCT_VALUE in", values, "productValue");
            return (Criteria) this;
        }

        public Criteria andProductValueNotIn(List<String> values) {
            addCriterion("PRODUCT_VALUE not in", values, "productValue");
            return (Criteria) this;
        }

        public Criteria andProductValueBetween(String value1, String value2) {
            addCriterion("PRODUCT_VALUE between", value1, value2, "productValue");
            return (Criteria) this;
        }

        public Criteria andProductValueNotBetween(String value1, String value2) {
            addCriterion("PRODUCT_VALUE not between", value1, value2, "productValue");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andResDescIsNull() {
            addCriterion("RES_DESC is null");
            return (Criteria) this;
        }

        public Criteria andResDescIsNotNull() {
            addCriterion("RES_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andResDescEqualTo(String value) {
            addCriterion("RES_DESC =", value, "resDesc");
            return (Criteria) this;
        }

        public Criteria andResDescNotEqualTo(String value) {
            addCriterion("RES_DESC <>", value, "resDesc");
            return (Criteria) this;
        }

        public Criteria andResDescGreaterThan(String value) {
            addCriterion("RES_DESC >", value, "resDesc");
            return (Criteria) this;
        }

        public Criteria andResDescGreaterThanOrEqualTo(String value) {
            addCriterion("RES_DESC >=", value, "resDesc");
            return (Criteria) this;
        }

        public Criteria andResDescLessThan(String value) {
            addCriterion("RES_DESC <", value, "resDesc");
            return (Criteria) this;
        }

        public Criteria andResDescLessThanOrEqualTo(String value) {
            addCriterion("RES_DESC <=", value, "resDesc");
            return (Criteria) this;
        }

        public Criteria andResDescLike(String value) {
            addCriterion("RES_DESC like", value, "resDesc");
            return (Criteria) this;
        }

        public Criteria andResDescNotLike(String value) {
            addCriterion("RES_DESC not like", value, "resDesc");
            return (Criteria) this;
        }

        public Criteria andResDescIn(List<String> values) {
            addCriterion("RES_DESC in", values, "resDesc");
            return (Criteria) this;
        }

        public Criteria andResDescNotIn(List<String> values) {
            addCriterion("RES_DESC not in", values, "resDesc");
            return (Criteria) this;
        }

        public Criteria andResDescBetween(String value1, String value2) {
            addCriterion("RES_DESC between", value1, value2, "resDesc");
            return (Criteria) this;
        }

        public Criteria andResDescNotBetween(String value1, String value2) {
            addCriterion("RES_DESC not between", value1, value2, "resDesc");
            return (Criteria) this;
        }

        public Criteria andAbilityDescIsNull() {
            addCriterion("ABILITY_DESC is null");
            return (Criteria) this;
        }

        public Criteria andAbilityDescIsNotNull() {
            addCriterion("ABILITY_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andAbilityDescEqualTo(String value) {
            addCriterion("ABILITY_DESC =", value, "abilityDesc");
            return (Criteria) this;
        }

        public Criteria andAbilityDescNotEqualTo(String value) {
            addCriterion("ABILITY_DESC <>", value, "abilityDesc");
            return (Criteria) this;
        }

        public Criteria andAbilityDescGreaterThan(String value) {
            addCriterion("ABILITY_DESC >", value, "abilityDesc");
            return (Criteria) this;
        }

        public Criteria andAbilityDescGreaterThanOrEqualTo(String value) {
            addCriterion("ABILITY_DESC >=", value, "abilityDesc");
            return (Criteria) this;
        }

        public Criteria andAbilityDescLessThan(String value) {
            addCriterion("ABILITY_DESC <", value, "abilityDesc");
            return (Criteria) this;
        }

        public Criteria andAbilityDescLessThanOrEqualTo(String value) {
            addCriterion("ABILITY_DESC <=", value, "abilityDesc");
            return (Criteria) this;
        }

        public Criteria andAbilityDescLike(String value) {
            addCriterion("ABILITY_DESC like", value, "abilityDesc");
            return (Criteria) this;
        }

        public Criteria andAbilityDescNotLike(String value) {
            addCriterion("ABILITY_DESC not like", value, "abilityDesc");
            return (Criteria) this;
        }

        public Criteria andAbilityDescIn(List<String> values) {
            addCriterion("ABILITY_DESC in", values, "abilityDesc");
            return (Criteria) this;
        }

        public Criteria andAbilityDescNotIn(List<String> values) {
            addCriterion("ABILITY_DESC not in", values, "abilityDesc");
            return (Criteria) this;
        }

        public Criteria andAbilityDescBetween(String value1, String value2) {
            addCriterion("ABILITY_DESC between", value1, value2, "abilityDesc");
            return (Criteria) this;
        }

        public Criteria andAbilityDescNotBetween(String value1, String value2) {
            addCriterion("ABILITY_DESC not between", value1, value2, "abilityDesc");
            return (Criteria) this;
        }

        public Criteria andJoinTimeIsNull() {
            addCriterion("JOIN_TIME is null");
            return (Criteria) this;
        }

        public Criteria andJoinTimeIsNotNull() {
            addCriterion("JOIN_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andJoinTimeEqualTo(Date value) {
            addCriterionForJDBCDate("JOIN_TIME =", value, "joinTime");
            return (Criteria) this;
        }

        public Criteria andJoinTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("JOIN_TIME <>", value, "joinTime");
            return (Criteria) this;
        }

        public Criteria andJoinTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("JOIN_TIME >", value, "joinTime");
            return (Criteria) this;
        }

        public Criteria andJoinTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("JOIN_TIME >=", value, "joinTime");
            return (Criteria) this;
        }

        public Criteria andJoinTimeLessThan(Date value) {
            addCriterionForJDBCDate("JOIN_TIME <", value, "joinTime");
            return (Criteria) this;
        }

        public Criteria andJoinTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("JOIN_TIME <=", value, "joinTime");
            return (Criteria) this;
        }

        public Criteria andJoinTimeIn(List<Date> values) {
            addCriterionForJDBCDate("JOIN_TIME in", values, "joinTime");
            return (Criteria) this;
        }

        public Criteria andJoinTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("JOIN_TIME not in", values, "joinTime");
            return (Criteria) this;
        }

        public Criteria andJoinTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("JOIN_TIME between", value1, value2, "joinTime");
            return (Criteria) this;
        }

        public Criteria andJoinTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("JOIN_TIME not between", value1, value2, "joinTime");
            return (Criteria) this;
        }

        public Criteria andServiceTimeIsNull() {
            addCriterion("SERVICE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andServiceTimeIsNotNull() {
            addCriterion("SERVICE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andServiceTimeEqualTo(Integer value) {
            addCriterion("SERVICE_TIME =", value, "serviceTime");
            return (Criteria) this;
        }

        public Criteria andServiceTimeNotEqualTo(Integer value) {
            addCriterion("SERVICE_TIME <>", value, "serviceTime");
            return (Criteria) this;
        }

        public Criteria andServiceTimeGreaterThan(Integer value) {
            addCriterion("SERVICE_TIME >", value, "serviceTime");
            return (Criteria) this;
        }

        public Criteria andServiceTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("SERVICE_TIME >=", value, "serviceTime");
            return (Criteria) this;
        }

        public Criteria andServiceTimeLessThan(Integer value) {
            addCriterion("SERVICE_TIME <", value, "serviceTime");
            return (Criteria) this;
        }

        public Criteria andServiceTimeLessThanOrEqualTo(Integer value) {
            addCriterion("SERVICE_TIME <=", value, "serviceTime");
            return (Criteria) this;
        }

        public Criteria andServiceTimeIn(List<Integer> values) {
            addCriterion("SERVICE_TIME in", values, "serviceTime");
            return (Criteria) this;
        }

        public Criteria andServiceTimeNotIn(List<Integer> values) {
            addCriterion("SERVICE_TIME not in", values, "serviceTime");
            return (Criteria) this;
        }

        public Criteria andServiceTimeBetween(Integer value1, Integer value2) {
            addCriterion("SERVICE_TIME between", value1, value2, "serviceTime");
            return (Criteria) this;
        }

        public Criteria andServiceTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("SERVICE_TIME not between", value1, value2, "serviceTime");
            return (Criteria) this;
        }

        public Criteria andServiceSuccessTimeIsNull() {
            addCriterion("SERVICE_SUCCESS_TIME is null");
            return (Criteria) this;
        }

        public Criteria andServiceSuccessTimeIsNotNull() {
            addCriterion("SERVICE_SUCCESS_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andServiceSuccessTimeEqualTo(Integer value) {
            addCriterion("SERVICE_SUCCESS_TIME =", value, "serviceSuccessTime");
            return (Criteria) this;
        }

        public Criteria andServiceSuccessTimeNotEqualTo(Integer value) {
            addCriterion("SERVICE_SUCCESS_TIME <>", value, "serviceSuccessTime");
            return (Criteria) this;
        }

        public Criteria andServiceSuccessTimeGreaterThan(Integer value) {
            addCriterion("SERVICE_SUCCESS_TIME >", value, "serviceSuccessTime");
            return (Criteria) this;
        }

        public Criteria andServiceSuccessTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("SERVICE_SUCCESS_TIME >=", value, "serviceSuccessTime");
            return (Criteria) this;
        }

        public Criteria andServiceSuccessTimeLessThan(Integer value) {
            addCriterion("SERVICE_SUCCESS_TIME <", value, "serviceSuccessTime");
            return (Criteria) this;
        }

        public Criteria andServiceSuccessTimeLessThanOrEqualTo(Integer value) {
            addCriterion("SERVICE_SUCCESS_TIME <=", value, "serviceSuccessTime");
            return (Criteria) this;
        }

        public Criteria andServiceSuccessTimeIn(List<Integer> values) {
            addCriterion("SERVICE_SUCCESS_TIME in", values, "serviceSuccessTime");
            return (Criteria) this;
        }

        public Criteria andServiceSuccessTimeNotIn(List<Integer> values) {
            addCriterion("SERVICE_SUCCESS_TIME not in", values, "serviceSuccessTime");
            return (Criteria) this;
        }

        public Criteria andServiceSuccessTimeBetween(Integer value1, Integer value2) {
            addCriterion("SERVICE_SUCCESS_TIME between", value1, value2, "serviceSuccessTime");
            return (Criteria) this;
        }

        public Criteria andServiceSuccessTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("SERVICE_SUCCESS_TIME not between", value1, value2, "serviceSuccessTime");
            return (Criteria) this;
        }

        public Criteria andProtocolUrlIsNull() {
            addCriterion("PROTOCOL_URL is null");
            return (Criteria) this;
        }

        public Criteria andProtocolUrlIsNotNull() {
            addCriterion("PROTOCOL_URL is not null");
            return (Criteria) this;
        }

        public Criteria andProtocolUrlEqualTo(String value) {
            addCriterion("PROTOCOL_URL =", value, "protocolUrl");
            return (Criteria) this;
        }

        public Criteria andProtocolUrlNotEqualTo(String value) {
            addCriterion("PROTOCOL_URL <>", value, "protocolUrl");
            return (Criteria) this;
        }

        public Criteria andProtocolUrlGreaterThan(String value) {
            addCriterion("PROTOCOL_URL >", value, "protocolUrl");
            return (Criteria) this;
        }

        public Criteria andProtocolUrlGreaterThanOrEqualTo(String value) {
            addCriterion("PROTOCOL_URL >=", value, "protocolUrl");
            return (Criteria) this;
        }

        public Criteria andProtocolUrlLessThan(String value) {
            addCriterion("PROTOCOL_URL <", value, "protocolUrl");
            return (Criteria) this;
        }

        public Criteria andProtocolUrlLessThanOrEqualTo(String value) {
            addCriterion("PROTOCOL_URL <=", value, "protocolUrl");
            return (Criteria) this;
        }

        public Criteria andProtocolUrlLike(String value) {
            addCriterion("PROTOCOL_URL like", value, "protocolUrl");
            return (Criteria) this;
        }

        public Criteria andProtocolUrlNotLike(String value) {
            addCriterion("PROTOCOL_URL not like", value, "protocolUrl");
            return (Criteria) this;
        }

        public Criteria andProtocolUrlIn(List<String> values) {
            addCriterion("PROTOCOL_URL in", values, "protocolUrl");
            return (Criteria) this;
        }

        public Criteria andProtocolUrlNotIn(List<String> values) {
            addCriterion("PROTOCOL_URL not in", values, "protocolUrl");
            return (Criteria) this;
        }

        public Criteria andProtocolUrlBetween(String value1, String value2) {
            addCriterion("PROTOCOL_URL between", value1, value2, "protocolUrl");
            return (Criteria) this;
        }

        public Criteria andProtocolUrlNotBetween(String value1, String value2) {
            addCriterion("PROTOCOL_URL not between", value1, value2, "protocolUrl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the trash table spt_member
     *
     * @mbg.generated do_not_delete_during_merge Tue Oct 08 21:52:23 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the trash table spt_member
     *
     * @mbg.generated Tue Oct 08 21:52:23 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}