package com.plateform.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class OrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table spt_order
     *
     * @mbg.generated Thu Oct 17 14:47:24 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table spt_order
     *
     * @mbg.generated Thu Oct 17 14:47:24 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table spt_order
     *
     * @mbg.generated Thu Oct 17 14:47:24 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spt_order
     *
     * @mbg.generated Thu Oct 17 14:47:24 CST 2019
     */
    public OrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spt_order
     *
     * @mbg.generated Thu Oct 17 14:47:24 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spt_order
     *
     * @mbg.generated Thu Oct 17 14:47:24 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spt_order
     *
     * @mbg.generated Thu Oct 17 14:47:24 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spt_order
     *
     * @mbg.generated Thu Oct 17 14:47:24 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spt_order
     *
     * @mbg.generated Thu Oct 17 14:47:24 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spt_order
     *
     * @mbg.generated Thu Oct 17 14:47:24 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spt_order
     *
     * @mbg.generated Thu Oct 17 14:47:24 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spt_order
     *
     * @mbg.generated Thu Oct 17 14:47:24 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spt_order
     *
     * @mbg.generated Thu Oct 17 14:47:24 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spt_order
     *
     * @mbg.generated Thu Oct 17 14:47:24 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table spt_order
     *
     * @mbg.generated Thu Oct 17 14:47:24 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDemandNoIsNull() {
            addCriterion("DEMAND_NO is null");
            return (Criteria) this;
        }

        public Criteria andDemandNoIsNotNull() {
            addCriterion("DEMAND_NO is not null");
            return (Criteria) this;
        }

        public Criteria andDemandNoEqualTo(String value) {
            addCriterion("DEMAND_NO =", value, "demandNo");
            return (Criteria) this;
        }

        public Criteria andDemandNoNotEqualTo(String value) {
            addCriterion("DEMAND_NO <>", value, "demandNo");
            return (Criteria) this;
        }

        public Criteria andDemandNoGreaterThan(String value) {
            addCriterion("DEMAND_NO >", value, "demandNo");
            return (Criteria) this;
        }

        public Criteria andDemandNoGreaterThanOrEqualTo(String value) {
            addCriterion("DEMAND_NO >=", value, "demandNo");
            return (Criteria) this;
        }

        public Criteria andDemandNoLessThan(String value) {
            addCriterion("DEMAND_NO <", value, "demandNo");
            return (Criteria) this;
        }

        public Criteria andDemandNoLessThanOrEqualTo(String value) {
            addCriterion("DEMAND_NO <=", value, "demandNo");
            return (Criteria) this;
        }

        public Criteria andDemandNoLike(String value) {
            addCriterion("DEMAND_NO like", value, "demandNo");
            return (Criteria) this;
        }

        public Criteria andDemandNoNotLike(String value) {
            addCriterion("DEMAND_NO not like", value, "demandNo");
            return (Criteria) this;
        }

        public Criteria andDemandNoIn(List<String> values) {
            addCriterion("DEMAND_NO in", values, "demandNo");
            return (Criteria) this;
        }

        public Criteria andDemandNoNotIn(List<String> values) {
            addCriterion("DEMAND_NO not in", values, "demandNo");
            return (Criteria) this;
        }

        public Criteria andDemandNoBetween(String value1, String value2) {
            addCriterion("DEMAND_NO between", value1, value2, "demandNo");
            return (Criteria) this;
        }

        public Criteria andDemandNoNotBetween(String value1, String value2) {
            addCriterion("DEMAND_NO not between", value1, value2, "demandNo");
            return (Criteria) this;
        }

        public Criteria andUserNoIsNull() {
            addCriterion("USER_NO is null");
            return (Criteria) this;
        }

        public Criteria andUserNoIsNotNull() {
            addCriterion("USER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andUserNoEqualTo(String value) {
            addCriterion("USER_NO =", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoNotEqualTo(String value) {
            addCriterion("USER_NO <>", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoGreaterThan(String value) {
            addCriterion("USER_NO >", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoGreaterThanOrEqualTo(String value) {
            addCriterion("USER_NO >=", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoLessThan(String value) {
            addCriterion("USER_NO <", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoLessThanOrEqualTo(String value) {
            addCriterion("USER_NO <=", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoLike(String value) {
            addCriterion("USER_NO like", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoNotLike(String value) {
            addCriterion("USER_NO not like", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoIn(List<String> values) {
            addCriterion("USER_NO in", values, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoNotIn(List<String> values) {
            addCriterion("USER_NO not in", values, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoBetween(String value1, String value2) {
            addCriterion("USER_NO between", value1, value2, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoNotBetween(String value1, String value2) {
            addCriterion("USER_NO not between", value1, value2, "userNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoIsNull() {
            addCriterion("MEMBER_NO is null");
            return (Criteria) this;
        }

        public Criteria andMemberNoIsNotNull() {
            addCriterion("MEMBER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andMemberNoEqualTo(String value) {
            addCriterion("MEMBER_NO =", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoNotEqualTo(String value) {
            addCriterion("MEMBER_NO <>", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoGreaterThan(String value) {
            addCriterion("MEMBER_NO >", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoGreaterThanOrEqualTo(String value) {
            addCriterion("MEMBER_NO >=", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoLessThan(String value) {
            addCriterion("MEMBER_NO <", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoLessThanOrEqualTo(String value) {
            addCriterion("MEMBER_NO <=", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoLike(String value) {
            addCriterion("MEMBER_NO like", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoNotLike(String value) {
            addCriterion("MEMBER_NO not like", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoIn(List<String> values) {
            addCriterion("MEMBER_NO in", values, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoNotIn(List<String> values) {
            addCriterion("MEMBER_NO not in", values, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoBetween(String value1, String value2) {
            addCriterion("MEMBER_NO between", value1, value2, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoNotBetween(String value1, String value2) {
            addCriterion("MEMBER_NO not between", value1, value2, "memberNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoIsNull() {
            addCriterion("ABILITY_NO is null");
            return (Criteria) this;
        }

        public Criteria andAbilityNoIsNotNull() {
            addCriterion("ABILITY_NO is not null");
            return (Criteria) this;
        }

        public Criteria andAbilityNoEqualTo(String value) {
            addCriterion("ABILITY_NO =", value, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoNotEqualTo(String value) {
            addCriterion("ABILITY_NO <>", value, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoGreaterThan(String value) {
            addCriterion("ABILITY_NO >", value, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoGreaterThanOrEqualTo(String value) {
            addCriterion("ABILITY_NO >=", value, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoLessThan(String value) {
            addCriterion("ABILITY_NO <", value, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoLessThanOrEqualTo(String value) {
            addCriterion("ABILITY_NO <=", value, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoLike(String value) {
            addCriterion("ABILITY_NO like", value, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoNotLike(String value) {
            addCriterion("ABILITY_NO not like", value, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoIn(List<String> values) {
            addCriterion("ABILITY_NO in", values, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoNotIn(List<String> values) {
            addCriterion("ABILITY_NO not in", values, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoBetween(String value1, String value2) {
            addCriterion("ABILITY_NO between", value1, value2, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoNotBetween(String value1, String value2) {
            addCriterion("ABILITY_NO not between", value1, value2, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andHandlerIsNull() {
            addCriterion("HANDLER is null");
            return (Criteria) this;
        }

        public Criteria andHandlerIsNotNull() {
            addCriterion("HANDLER is not null");
            return (Criteria) this;
        }

        public Criteria andHandlerEqualTo(String value) {
            addCriterion("HANDLER =", value, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerNotEqualTo(String value) {
            addCriterion("HANDLER <>", value, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerGreaterThan(String value) {
            addCriterion("HANDLER >", value, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerGreaterThanOrEqualTo(String value) {
            addCriterion("HANDLER >=", value, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerLessThan(String value) {
            addCriterion("HANDLER <", value, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerLessThanOrEqualTo(String value) {
            addCriterion("HANDLER <=", value, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerLike(String value) {
            addCriterion("HANDLER like", value, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerNotLike(String value) {
            addCriterion("HANDLER not like", value, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerIn(List<String> values) {
            addCriterion("HANDLER in", values, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerNotIn(List<String> values) {
            addCriterion("HANDLER not in", values, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerBetween(String value1, String value2) {
            addCriterion("HANDLER between", value1, value2, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerNotBetween(String value1, String value2) {
            addCriterion("HANDLER not between", value1, value2, "handler");
            return (Criteria) this;
        }

        public Criteria andGeneratedTimeIsNull() {
            addCriterion("GENERATED_TIME is null");
            return (Criteria) this;
        }

        public Criteria andGeneratedTimeIsNotNull() {
            addCriterion("GENERATED_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andGeneratedTimeEqualTo(Date value) {
            addCriterionForJDBCDate("GENERATED_TIME =", value, "generatedTime");
            return (Criteria) this;
        }

        public Criteria andGeneratedTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("GENERATED_TIME <>", value, "generatedTime");
            return (Criteria) this;
        }

        public Criteria andGeneratedTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("GENERATED_TIME >", value, "generatedTime");
            return (Criteria) this;
        }

        public Criteria andGeneratedTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("GENERATED_TIME >=", value, "generatedTime");
            return (Criteria) this;
        }

        public Criteria andGeneratedTimeLessThan(Date value) {
            addCriterionForJDBCDate("GENERATED_TIME <", value, "generatedTime");
            return (Criteria) this;
        }

        public Criteria andGeneratedTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("GENERATED_TIME <=", value, "generatedTime");
            return (Criteria) this;
        }

        public Criteria andGeneratedTimeIn(List<Date> values) {
            addCriterionForJDBCDate("GENERATED_TIME in", values, "generatedTime");
            return (Criteria) this;
        }

        public Criteria andGeneratedTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("GENERATED_TIME not in", values, "generatedTime");
            return (Criteria) this;
        }

        public Criteria andGeneratedTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("GENERATED_TIME between", value1, value2, "generatedTime");
            return (Criteria) this;
        }

        public Criteria andGeneratedTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("GENERATED_TIME not between", value1, value2, "generatedTime");
            return (Criteria) this;
        }

        public Criteria andUserOpinionIsNull() {
            addCriterion("USER_OPINION is null");
            return (Criteria) this;
        }

        public Criteria andUserOpinionIsNotNull() {
            addCriterion("USER_OPINION is not null");
            return (Criteria) this;
        }

        public Criteria andUserOpinionEqualTo(String value) {
            addCriterion("USER_OPINION =", value, "userOpinion");
            return (Criteria) this;
        }

        public Criteria andUserOpinionNotEqualTo(String value) {
            addCriterion("USER_OPINION <>", value, "userOpinion");
            return (Criteria) this;
        }

        public Criteria andUserOpinionGreaterThan(String value) {
            addCriterion("USER_OPINION >", value, "userOpinion");
            return (Criteria) this;
        }

        public Criteria andUserOpinionGreaterThanOrEqualTo(String value) {
            addCriterion("USER_OPINION >=", value, "userOpinion");
            return (Criteria) this;
        }

        public Criteria andUserOpinionLessThan(String value) {
            addCriterion("USER_OPINION <", value, "userOpinion");
            return (Criteria) this;
        }

        public Criteria andUserOpinionLessThanOrEqualTo(String value) {
            addCriterion("USER_OPINION <=", value, "userOpinion");
            return (Criteria) this;
        }

        public Criteria andUserOpinionLike(String value) {
            addCriterion("USER_OPINION like", value, "userOpinion");
            return (Criteria) this;
        }

        public Criteria andUserOpinionNotLike(String value) {
            addCriterion("USER_OPINION not like", value, "userOpinion");
            return (Criteria) this;
        }

        public Criteria andUserOpinionIn(List<String> values) {
            addCriterion("USER_OPINION in", values, "userOpinion");
            return (Criteria) this;
        }

        public Criteria andUserOpinionNotIn(List<String> values) {
            addCriterion("USER_OPINION not in", values, "userOpinion");
            return (Criteria) this;
        }

        public Criteria andUserOpinionBetween(String value1, String value2) {
            addCriterion("USER_OPINION between", value1, value2, "userOpinion");
            return (Criteria) this;
        }

        public Criteria andUserOpinionNotBetween(String value1, String value2) {
            addCriterion("USER_OPINION not between", value1, value2, "userOpinion");
            return (Criteria) this;
        }

        public Criteria andMemberOpinionIsNull() {
            addCriterion("MEMBER_OPINION is null");
            return (Criteria) this;
        }

        public Criteria andMemberOpinionIsNotNull() {
            addCriterion("MEMBER_OPINION is not null");
            return (Criteria) this;
        }

        public Criteria andMemberOpinionEqualTo(String value) {
            addCriterion("MEMBER_OPINION =", value, "memberOpinion");
            return (Criteria) this;
        }

        public Criteria andMemberOpinionNotEqualTo(String value) {
            addCriterion("MEMBER_OPINION <>", value, "memberOpinion");
            return (Criteria) this;
        }

        public Criteria andMemberOpinionGreaterThan(String value) {
            addCriterion("MEMBER_OPINION >", value, "memberOpinion");
            return (Criteria) this;
        }

        public Criteria andMemberOpinionGreaterThanOrEqualTo(String value) {
            addCriterion("MEMBER_OPINION >=", value, "memberOpinion");
            return (Criteria) this;
        }

        public Criteria andMemberOpinionLessThan(String value) {
            addCriterion("MEMBER_OPINION <", value, "memberOpinion");
            return (Criteria) this;
        }

        public Criteria andMemberOpinionLessThanOrEqualTo(String value) {
            addCriterion("MEMBER_OPINION <=", value, "memberOpinion");
            return (Criteria) this;
        }

        public Criteria andMemberOpinionLike(String value) {
            addCriterion("MEMBER_OPINION like", value, "memberOpinion");
            return (Criteria) this;
        }

        public Criteria andMemberOpinionNotLike(String value) {
            addCriterion("MEMBER_OPINION not like", value, "memberOpinion");
            return (Criteria) this;
        }

        public Criteria andMemberOpinionIn(List<String> values) {
            addCriterion("MEMBER_OPINION in", values, "memberOpinion");
            return (Criteria) this;
        }

        public Criteria andMemberOpinionNotIn(List<String> values) {
            addCriterion("MEMBER_OPINION not in", values, "memberOpinion");
            return (Criteria) this;
        }

        public Criteria andMemberOpinionBetween(String value1, String value2) {
            addCriterion("MEMBER_OPINION between", value1, value2, "memberOpinion");
            return (Criteria) this;
        }

        public Criteria andMemberOpinionNotBetween(String value1, String value2) {
            addCriterion("MEMBER_OPINION not between", value1, value2, "memberOpinion");
            return (Criteria) this;
        }

        public Criteria andAdminOpinionIsNull() {
            addCriterion("ADMIN_OPINION is null");
            return (Criteria) this;
        }

        public Criteria andAdminOpinionIsNotNull() {
            addCriterion("ADMIN_OPINION is not null");
            return (Criteria) this;
        }

        public Criteria andAdminOpinionEqualTo(String value) {
            addCriterion("ADMIN_OPINION =", value, "adminOpinion");
            return (Criteria) this;
        }

        public Criteria andAdminOpinionNotEqualTo(String value) {
            addCriterion("ADMIN_OPINION <>", value, "adminOpinion");
            return (Criteria) this;
        }

        public Criteria andAdminOpinionGreaterThan(String value) {
            addCriterion("ADMIN_OPINION >", value, "adminOpinion");
            return (Criteria) this;
        }

        public Criteria andAdminOpinionGreaterThanOrEqualTo(String value) {
            addCriterion("ADMIN_OPINION >=", value, "adminOpinion");
            return (Criteria) this;
        }

        public Criteria andAdminOpinionLessThan(String value) {
            addCriterion("ADMIN_OPINION <", value, "adminOpinion");
            return (Criteria) this;
        }

        public Criteria andAdminOpinionLessThanOrEqualTo(String value) {
            addCriterion("ADMIN_OPINION <=", value, "adminOpinion");
            return (Criteria) this;
        }

        public Criteria andAdminOpinionLike(String value) {
            addCriterion("ADMIN_OPINION like", value, "adminOpinion");
            return (Criteria) this;
        }

        public Criteria andAdminOpinionNotLike(String value) {
            addCriterion("ADMIN_OPINION not like", value, "adminOpinion");
            return (Criteria) this;
        }

        public Criteria andAdminOpinionIn(List<String> values) {
            addCriterion("ADMIN_OPINION in", values, "adminOpinion");
            return (Criteria) this;
        }

        public Criteria andAdminOpinionNotIn(List<String> values) {
            addCriterion("ADMIN_OPINION not in", values, "adminOpinion");
            return (Criteria) this;
        }

        public Criteria andAdminOpinionBetween(String value1, String value2) {
            addCriterion("ADMIN_OPINION between", value1, value2, "adminOpinion");
            return (Criteria) this;
        }

        public Criteria andAdminOpinionNotBetween(String value1, String value2) {
            addCriterion("ADMIN_OPINION not between", value1, value2, "adminOpinion");
            return (Criteria) this;
        }

        public Criteria andMeetingResultIsNull() {
            addCriterion("MEETING_RESULT is null");
            return (Criteria) this;
        }

        public Criteria andMeetingResultIsNotNull() {
            addCriterion("MEETING_RESULT is not null");
            return (Criteria) this;
        }

        public Criteria andMeetingResultEqualTo(String value) {
            addCriterion("MEETING_RESULT =", value, "meetingResult");
            return (Criteria) this;
        }

        public Criteria andMeetingResultNotEqualTo(String value) {
            addCriterion("MEETING_RESULT <>", value, "meetingResult");
            return (Criteria) this;
        }

        public Criteria andMeetingResultGreaterThan(String value) {
            addCriterion("MEETING_RESULT >", value, "meetingResult");
            return (Criteria) this;
        }

        public Criteria andMeetingResultGreaterThanOrEqualTo(String value) {
            addCriterion("MEETING_RESULT >=", value, "meetingResult");
            return (Criteria) this;
        }

        public Criteria andMeetingResultLessThan(String value) {
            addCriterion("MEETING_RESULT <", value, "meetingResult");
            return (Criteria) this;
        }

        public Criteria andMeetingResultLessThanOrEqualTo(String value) {
            addCriterion("MEETING_RESULT <=", value, "meetingResult");
            return (Criteria) this;
        }

        public Criteria andMeetingResultLike(String value) {
            addCriterion("MEETING_RESULT like", value, "meetingResult");
            return (Criteria) this;
        }

        public Criteria andMeetingResultNotLike(String value) {
            addCriterion("MEETING_RESULT not like", value, "meetingResult");
            return (Criteria) this;
        }

        public Criteria andMeetingResultIn(List<String> values) {
            addCriterion("MEETING_RESULT in", values, "meetingResult");
            return (Criteria) this;
        }

        public Criteria andMeetingResultNotIn(List<String> values) {
            addCriterion("MEETING_RESULT not in", values, "meetingResult");
            return (Criteria) this;
        }

        public Criteria andMeetingResultBetween(String value1, String value2) {
            addCriterion("MEETING_RESULT between", value1, value2, "meetingResult");
            return (Criteria) this;
        }

        public Criteria andMeetingResultNotBetween(String value1, String value2) {
            addCriterion("MEETING_RESULT not between", value1, value2, "meetingResult");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andSolveTimeIsNull() {
            addCriterion("SOLVE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andSolveTimeIsNotNull() {
            addCriterion("SOLVE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andSolveTimeEqualTo(Date value) {
            addCriterionForJDBCDate("SOLVE_TIME =", value, "solveTime");
            return (Criteria) this;
        }

        public Criteria andSolveTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("SOLVE_TIME <>", value, "solveTime");
            return (Criteria) this;
        }

        public Criteria andSolveTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("SOLVE_TIME >", value, "solveTime");
            return (Criteria) this;
        }

        public Criteria andSolveTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SOLVE_TIME >=", value, "solveTime");
            return (Criteria) this;
        }

        public Criteria andSolveTimeLessThan(Date value) {
            addCriterionForJDBCDate("SOLVE_TIME <", value, "solveTime");
            return (Criteria) this;
        }

        public Criteria andSolveTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SOLVE_TIME <=", value, "solveTime");
            return (Criteria) this;
        }

        public Criteria andSolveTimeIn(List<Date> values) {
            addCriterionForJDBCDate("SOLVE_TIME in", values, "solveTime");
            return (Criteria) this;
        }

        public Criteria andSolveTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("SOLVE_TIME not in", values, "solveTime");
            return (Criteria) this;
        }

        public Criteria andSolveTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SOLVE_TIME between", value1, value2, "solveTime");
            return (Criteria) this;
        }

        public Criteria andSolveTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SOLVE_TIME not between", value1, value2, "solveTime");
            return (Criteria) this;
        }

        public Criteria andContractAmountIsNull() {
            addCriterion("CONTRACT_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andContractAmountIsNotNull() {
            addCriterion("CONTRACT_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andContractAmountEqualTo(String value) {
            addCriterion("CONTRACT_AMOUNT =", value, "contractAmount");
            return (Criteria) this;
        }

        public Criteria andContractAmountNotEqualTo(String value) {
            addCriterion("CONTRACT_AMOUNT <>", value, "contractAmount");
            return (Criteria) this;
        }

        public Criteria andContractAmountGreaterThan(String value) {
            addCriterion("CONTRACT_AMOUNT >", value, "contractAmount");
            return (Criteria) this;
        }

        public Criteria andContractAmountGreaterThanOrEqualTo(String value) {
            addCriterion("CONTRACT_AMOUNT >=", value, "contractAmount");
            return (Criteria) this;
        }

        public Criteria andContractAmountLessThan(String value) {
            addCriterion("CONTRACT_AMOUNT <", value, "contractAmount");
            return (Criteria) this;
        }

        public Criteria andContractAmountLessThanOrEqualTo(String value) {
            addCriterion("CONTRACT_AMOUNT <=", value, "contractAmount");
            return (Criteria) this;
        }

        public Criteria andContractAmountLike(String value) {
            addCriterion("CONTRACT_AMOUNT like", value, "contractAmount");
            return (Criteria) this;
        }

        public Criteria andContractAmountNotLike(String value) {
            addCriterion("CONTRACT_AMOUNT not like", value, "contractAmount");
            return (Criteria) this;
        }

        public Criteria andContractAmountIn(List<String> values) {
            addCriterion("CONTRACT_AMOUNT in", values, "contractAmount");
            return (Criteria) this;
        }

        public Criteria andContractAmountNotIn(List<String> values) {
            addCriterion("CONTRACT_AMOUNT not in", values, "contractAmount");
            return (Criteria) this;
        }

        public Criteria andContractAmountBetween(String value1, String value2) {
            addCriterion("CONTRACT_AMOUNT between", value1, value2, "contractAmount");
            return (Criteria) this;
        }

        public Criteria andContractAmountNotBetween(String value1, String value2) {
            addCriterion("CONTRACT_AMOUNT not between", value1, value2, "contractAmount");
            return (Criteria) this;
        }

        public Criteria andUserEvaluationIsNull() {
            addCriterion("USER_EVALUATION is null");
            return (Criteria) this;
        }

        public Criteria andUserEvaluationIsNotNull() {
            addCriterion("USER_EVALUATION is not null");
            return (Criteria) this;
        }

        public Criteria andUserEvaluationEqualTo(String value) {
            addCriterion("USER_EVALUATION =", value, "userEvaluation");
            return (Criteria) this;
        }

        public Criteria andUserEvaluationNotEqualTo(String value) {
            addCriterion("USER_EVALUATION <>", value, "userEvaluation");
            return (Criteria) this;
        }

        public Criteria andUserEvaluationGreaterThan(String value) {
            addCriterion("USER_EVALUATION >", value, "userEvaluation");
            return (Criteria) this;
        }

        public Criteria andUserEvaluationGreaterThanOrEqualTo(String value) {
            addCriterion("USER_EVALUATION >=", value, "userEvaluation");
            return (Criteria) this;
        }

        public Criteria andUserEvaluationLessThan(String value) {
            addCriterion("USER_EVALUATION <", value, "userEvaluation");
            return (Criteria) this;
        }

        public Criteria andUserEvaluationLessThanOrEqualTo(String value) {
            addCriterion("USER_EVALUATION <=", value, "userEvaluation");
            return (Criteria) this;
        }

        public Criteria andUserEvaluationLike(String value) {
            addCriterion("USER_EVALUATION like", value, "userEvaluation");
            return (Criteria) this;
        }

        public Criteria andUserEvaluationNotLike(String value) {
            addCriterion("USER_EVALUATION not like", value, "userEvaluation");
            return (Criteria) this;
        }

        public Criteria andUserEvaluationIn(List<String> values) {
            addCriterion("USER_EVALUATION in", values, "userEvaluation");
            return (Criteria) this;
        }

        public Criteria andUserEvaluationNotIn(List<String> values) {
            addCriterion("USER_EVALUATION not in", values, "userEvaluation");
            return (Criteria) this;
        }

        public Criteria andUserEvaluationBetween(String value1, String value2) {
            addCriterion("USER_EVALUATION between", value1, value2, "userEvaluation");
            return (Criteria) this;
        }

        public Criteria andUserEvaluationNotBetween(String value1, String value2) {
            addCriterion("USER_EVALUATION not between", value1, value2, "userEvaluation");
            return (Criteria) this;
        }

        public Criteria andMemberEvaluationIsNull() {
            addCriterion("MEMBER_EVALUATION is null");
            return (Criteria) this;
        }

        public Criteria andMemberEvaluationIsNotNull() {
            addCriterion("MEMBER_EVALUATION is not null");
            return (Criteria) this;
        }

        public Criteria andMemberEvaluationEqualTo(String value) {
            addCriterion("MEMBER_EVALUATION =", value, "memberEvaluation");
            return (Criteria) this;
        }

        public Criteria andMemberEvaluationNotEqualTo(String value) {
            addCriterion("MEMBER_EVALUATION <>", value, "memberEvaluation");
            return (Criteria) this;
        }

        public Criteria andMemberEvaluationGreaterThan(String value) {
            addCriterion("MEMBER_EVALUATION >", value, "memberEvaluation");
            return (Criteria) this;
        }

        public Criteria andMemberEvaluationGreaterThanOrEqualTo(String value) {
            addCriterion("MEMBER_EVALUATION >=", value, "memberEvaluation");
            return (Criteria) this;
        }

        public Criteria andMemberEvaluationLessThan(String value) {
            addCriterion("MEMBER_EVALUATION <", value, "memberEvaluation");
            return (Criteria) this;
        }

        public Criteria andMemberEvaluationLessThanOrEqualTo(String value) {
            addCriterion("MEMBER_EVALUATION <=", value, "memberEvaluation");
            return (Criteria) this;
        }

        public Criteria andMemberEvaluationLike(String value) {
            addCriterion("MEMBER_EVALUATION like", value, "memberEvaluation");
            return (Criteria) this;
        }

        public Criteria andMemberEvaluationNotLike(String value) {
            addCriterion("MEMBER_EVALUATION not like", value, "memberEvaluation");
            return (Criteria) this;
        }

        public Criteria andMemberEvaluationIn(List<String> values) {
            addCriterion("MEMBER_EVALUATION in", values, "memberEvaluation");
            return (Criteria) this;
        }

        public Criteria andMemberEvaluationNotIn(List<String> values) {
            addCriterion("MEMBER_EVALUATION not in", values, "memberEvaluation");
            return (Criteria) this;
        }

        public Criteria andMemberEvaluationBetween(String value1, String value2) {
            addCriterion("MEMBER_EVALUATION between", value1, value2, "memberEvaluation");
            return (Criteria) this;
        }

        public Criteria andMemberEvaluationNotBetween(String value1, String value2) {
            addCriterion("MEMBER_EVALUATION not between", value1, value2, "memberEvaluation");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table spt_order
     *
     * @mbg.generated do_not_delete_during_merge Thu Oct 17 14:47:24 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table spt_order
     *
     * @mbg.generated Thu Oct 17 14:47:24 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}