package com.plateform.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Sres implements EncodableEntity {

    private Integer id;
    private String abilityNo;
    private String memberNo;
    private String abilityDescription;
    private String researchDirection;
    private String teamResourceDesc;
    private String teamBelongTo;
    private String abilityBase;
    private String otherResource;
    private String sharingCondition;
    private String costEstimate;
    private String remark;
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    private Date joinTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column sres.ID
     *
     * @return the value of sres.ID
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column sres.ID
     *
     * @param id the value for sres.ID
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column sres.ABILITY_NO
     *
     * @return the value of sres.ABILITY_NO
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public String getAbilityNo() {
        return abilityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column sres.ABILITY_NO
     *
     * @param abilityNo the value for sres.ABILITY_NO
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setAbilityNo(String abilityNo) {
        this.abilityNo = abilityNo == null ? null : abilityNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column sres.MEMBER_NO
     *
     * @return the value of sres.MEMBER_NO
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public String getMemberNo() {
        return memberNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column sres.MEMBER_NO
     *
     * @param memberNo the value for sres.MEMBER_NO
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setMemberNo(String memberNo) {
        this.memberNo = memberNo == null ? null : memberNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column sres.ABILITY_DESCRIPTION
     *
     * @return the value of sres.ABILITY_DESCRIPTION
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public String getAbilityDescription() {
        return abilityDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column sres.ABILITY_DESCRIPTION
     *
     * @param abilityDescription the value for sres.ABILITY_DESCRIPTION
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setAbilityDescription(String abilityDescription) {
        this.abilityDescription = abilityDescription == null ? null : abilityDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column sres.RESEARCH_DIRECTION
     *
     * @return the value of sres.RESEARCH_DIRECTION
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public String getResearchDirection() {
        return researchDirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column sres.RESEARCH_DIRECTION
     *
     * @param researchDirection the value for sres.RESEARCH_DIRECTION
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setResearchDirection(String researchDirection) {
        this.researchDirection = researchDirection == null ? null : researchDirection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column sres.TEAM_RESOURCE_DESC
     *
     * @return the value of sres.TEAM_RESOURCE_DESC
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public String getTeamResourceDesc() {
        return teamResourceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column sres.TEAM_RESOURCE_DESC
     *
     * @param teamResourceDesc the value for sres.TEAM_RESOURCE_DESC
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setTeamResourceDesc(String teamResourceDesc) {
        this.teamResourceDesc = teamResourceDesc == null ? null : teamResourceDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column sres.TEAM_BELONG_TO
     *
     * @return the value of sres.TEAM_BELONG_TO
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public String getTeamBelongTo() {
        return teamBelongTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column sres.TEAM_BELONG_TO
     *
     * @param teamBelongTo the value for sres.TEAM_BELONG_TO
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setTeamBelongTo(String teamBelongTo) {
        this.teamBelongTo = teamBelongTo == null ? null : teamBelongTo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column sres.ABILITY_BASE
     *
     * @return the value of sres.ABILITY_BASE
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public String getAbilityBase() {
        return abilityBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column sres.ABILITY_BASE
     *
     * @param abilityBase the value for sres.ABILITY_BASE
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setAbilityBase(String abilityBase) {
        this.abilityBase = abilityBase == null ? null : abilityBase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column sres.OTHER_RESOURCE
     *
     * @return the value of sres.OTHER_RESOURCE
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public String getOtherResource() {
        return otherResource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column sres.OTHER_RESOURCE
     *
     * @param otherResource the value for sres.OTHER_RESOURCE
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setOtherResource(String otherResource) {
        this.otherResource = otherResource == null ? null : otherResource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column sres.SHARING_CONDITION
     *
     * @return the value of sres.SHARING_CONDITION
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public String getSharingCondition() {
        return sharingCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column sres.SHARING_CONDITION
     *
     * @param sharingCondition the value for sres.SHARING_CONDITION
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setSharingCondition(String sharingCondition) {
        this.sharingCondition = sharingCondition == null ? null : sharingCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column sres.COST_ESTIMATE
     *
     * @return the value of sres.COST_ESTIMATE
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public String getCostEstimate() {
        return costEstimate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column sres.COST_ESTIMATE
     *
     * @param costEstimate the value for sres.COST_ESTIMATE
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setCostEstimate(String costEstimate) {
        this.costEstimate = costEstimate == null ? null : costEstimate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column sres.REMARK
     *
     * @return the value of sres.REMARK
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column sres.REMARK
     *
     * @param remark the value for sres.REMARK
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column sres.JOIN_TIME
     *
     * @return the value of sres.JOIN_TIME
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public Date getJoinTime() {
        return joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column sres.JOIN_TIME
     *
     * @param joinTime the value for sres.JOIN_TIME
     *
     * @mbg.generated Fri Sep 20 17:52:45 CST 2019
     */
    public void setJoinTime(Date joinTime) {
        this.joinTime = joinTime;
    }
}