package com.plateform.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class SresExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the trash table spp_sres
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the trash table spp_sres
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the trash table spp_sres
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_sres
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    public SresExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_sres
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_sres
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_sres
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_sres
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_sres
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_sres
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_sres
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_sres
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_sres
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_sres
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the trash table spp_sres
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAbilityNoIsNull() {
            addCriterion("ABILITY_NO is null");
            return (Criteria) this;
        }

        public Criteria andAbilityNoIsNotNull() {
            addCriterion("ABILITY_NO is not null");
            return (Criteria) this;
        }

        public Criteria andAbilityNoEqualTo(String value) {
            addCriterion("ABILITY_NO =", value, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoNotEqualTo(String value) {
            addCriterion("ABILITY_NO <>", value, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoGreaterThan(String value) {
            addCriterion("ABILITY_NO >", value, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoGreaterThanOrEqualTo(String value) {
            addCriterion("ABILITY_NO >=", value, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoLessThan(String value) {
            addCriterion("ABILITY_NO <", value, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoLessThanOrEqualTo(String value) {
            addCriterion("ABILITY_NO <=", value, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoLike(String value) {
            addCriterion("ABILITY_NO like", value, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoNotLike(String value) {
            addCriterion("ABILITY_NO not like", value, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoIn(List<String> values) {
            addCriterion("ABILITY_NO in", values, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoNotIn(List<String> values) {
            addCriterion("ABILITY_NO not in", values, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoBetween(String value1, String value2) {
            addCriterion("ABILITY_NO between", value1, value2, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoNotBetween(String value1, String value2) {
            addCriterion("ABILITY_NO not between", value1, value2, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoIsNull() {
            addCriterion("MEMBER_NO is null");
            return (Criteria) this;
        }

        public Criteria andMemberNoIsNotNull() {
            addCriterion("MEMBER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andMemberNoEqualTo(String value) {
            addCriterion("MEMBER_NO =", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoNotEqualTo(String value) {
            addCriterion("MEMBER_NO <>", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoGreaterThan(String value) {
            addCriterion("MEMBER_NO >", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoGreaterThanOrEqualTo(String value) {
            addCriterion("MEMBER_NO >=", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoLessThan(String value) {
            addCriterion("MEMBER_NO <", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoLessThanOrEqualTo(String value) {
            addCriterion("MEMBER_NO <=", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoLike(String value) {
            addCriterion("MEMBER_NO like", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoNotLike(String value) {
            addCriterion("MEMBER_NO not like", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoIn(List<String> values) {
            addCriterion("MEMBER_NO in", values, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoNotIn(List<String> values) {
            addCriterion("MEMBER_NO not in", values, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoBetween(String value1, String value2) {
            addCriterion("MEMBER_NO between", value1, value2, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoNotBetween(String value1, String value2) {
            addCriterion("MEMBER_NO not between", value1, value2, "memberNo");
            return (Criteria) this;
        }

        public Criteria andAbilityDescriptionIsNull() {
            addCriterion("ABILITY_DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andAbilityDescriptionIsNotNull() {
            addCriterion("ABILITY_DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andAbilityDescriptionEqualTo(String value) {
            addCriterion("ABILITY_DESCRIPTION =", value, "abilityDescription");
            return (Criteria) this;
        }

        public Criteria andAbilityDescriptionNotEqualTo(String value) {
            addCriterion("ABILITY_DESCRIPTION <>", value, "abilityDescription");
            return (Criteria) this;
        }

        public Criteria andAbilityDescriptionGreaterThan(String value) {
            addCriterion("ABILITY_DESCRIPTION >", value, "abilityDescription");
            return (Criteria) this;
        }

        public Criteria andAbilityDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("ABILITY_DESCRIPTION >=", value, "abilityDescription");
            return (Criteria) this;
        }

        public Criteria andAbilityDescriptionLessThan(String value) {
            addCriterion("ABILITY_DESCRIPTION <", value, "abilityDescription");
            return (Criteria) this;
        }

        public Criteria andAbilityDescriptionLessThanOrEqualTo(String value) {
            addCriterion("ABILITY_DESCRIPTION <=", value, "abilityDescription");
            return (Criteria) this;
        }

        public Criteria andAbilityDescriptionLike(String value) {
            addCriterion("ABILITY_DESCRIPTION like", value, "abilityDescription");
            return (Criteria) this;
        }

        public Criteria andAbilityDescriptionNotLike(String value) {
            addCriterion("ABILITY_DESCRIPTION not like", value, "abilityDescription");
            return (Criteria) this;
        }

        public Criteria andAbilityDescriptionIn(List<String> values) {
            addCriterion("ABILITY_DESCRIPTION in", values, "abilityDescription");
            return (Criteria) this;
        }

        public Criteria andAbilityDescriptionNotIn(List<String> values) {
            addCriterion("ABILITY_DESCRIPTION not in", values, "abilityDescription");
            return (Criteria) this;
        }

        public Criteria andAbilityDescriptionBetween(String value1, String value2) {
            addCriterion("ABILITY_DESCRIPTION between", value1, value2, "abilityDescription");
            return (Criteria) this;
        }

        public Criteria andAbilityDescriptionNotBetween(String value1, String value2) {
            addCriterion("ABILITY_DESCRIPTION not between", value1, value2, "abilityDescription");
            return (Criteria) this;
        }

        public Criteria andResearchDirectionIsNull() {
            addCriterion("RESEARCH_DIRECTION is null");
            return (Criteria) this;
        }

        public Criteria andResearchDirectionIsNotNull() {
            addCriterion("RESEARCH_DIRECTION is not null");
            return (Criteria) this;
        }

        public Criteria andResearchDirectionEqualTo(String value) {
            addCriterion("RESEARCH_DIRECTION =", value, "researchDirection");
            return (Criteria) this;
        }

        public Criteria andResearchDirectionNotEqualTo(String value) {
            addCriterion("RESEARCH_DIRECTION <>", value, "researchDirection");
            return (Criteria) this;
        }

        public Criteria andResearchDirectionGreaterThan(String value) {
            addCriterion("RESEARCH_DIRECTION >", value, "researchDirection");
            return (Criteria) this;
        }

        public Criteria andResearchDirectionGreaterThanOrEqualTo(String value) {
            addCriterion("RESEARCH_DIRECTION >=", value, "researchDirection");
            return (Criteria) this;
        }

        public Criteria andResearchDirectionLessThan(String value) {
            addCriterion("RESEARCH_DIRECTION <", value, "researchDirection");
            return (Criteria) this;
        }

        public Criteria andResearchDirectionLessThanOrEqualTo(String value) {
            addCriterion("RESEARCH_DIRECTION <=", value, "researchDirection");
            return (Criteria) this;
        }

        public Criteria andResearchDirectionLike(String value) {
            addCriterion("RESEARCH_DIRECTION like", value, "researchDirection");
            return (Criteria) this;
        }

        public Criteria andResearchDirectionNotLike(String value) {
            addCriterion("RESEARCH_DIRECTION not like", value, "researchDirection");
            return (Criteria) this;
        }

        public Criteria andResearchDirectionIn(List<String> values) {
            addCriterion("RESEARCH_DIRECTION in", values, "researchDirection");
            return (Criteria) this;
        }

        public Criteria andResearchDirectionNotIn(List<String> values) {
            addCriterion("RESEARCH_DIRECTION not in", values, "researchDirection");
            return (Criteria) this;
        }

        public Criteria andResearchDirectionBetween(String value1, String value2) {
            addCriterion("RESEARCH_DIRECTION between", value1, value2, "researchDirection");
            return (Criteria) this;
        }

        public Criteria andResearchDirectionNotBetween(String value1, String value2) {
            addCriterion("RESEARCH_DIRECTION not between", value1, value2, "researchDirection");
            return (Criteria) this;
        }

        public Criteria andTeamResourceDescIsNull() {
            addCriterion("TEAM_RESOURCE_DESC is null");
            return (Criteria) this;
        }

        public Criteria andTeamResourceDescIsNotNull() {
            addCriterion("TEAM_RESOURCE_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andTeamResourceDescEqualTo(String value) {
            addCriterion("TEAM_RESOURCE_DESC =", value, "teamResourceDesc");
            return (Criteria) this;
        }

        public Criteria andTeamResourceDescNotEqualTo(String value) {
            addCriterion("TEAM_RESOURCE_DESC <>", value, "teamResourceDesc");
            return (Criteria) this;
        }

        public Criteria andTeamResourceDescGreaterThan(String value) {
            addCriterion("TEAM_RESOURCE_DESC >", value, "teamResourceDesc");
            return (Criteria) this;
        }

        public Criteria andTeamResourceDescGreaterThanOrEqualTo(String value) {
            addCriterion("TEAM_RESOURCE_DESC >=", value, "teamResourceDesc");
            return (Criteria) this;
        }

        public Criteria andTeamResourceDescLessThan(String value) {
            addCriterion("TEAM_RESOURCE_DESC <", value, "teamResourceDesc");
            return (Criteria) this;
        }

        public Criteria andTeamResourceDescLessThanOrEqualTo(String value) {
            addCriterion("TEAM_RESOURCE_DESC <=", value, "teamResourceDesc");
            return (Criteria) this;
        }

        public Criteria andTeamResourceDescLike(String value) {
            addCriterion("TEAM_RESOURCE_DESC like", value, "teamResourceDesc");
            return (Criteria) this;
        }

        public Criteria andTeamResourceDescNotLike(String value) {
            addCriterion("TEAM_RESOURCE_DESC not like", value, "teamResourceDesc");
            return (Criteria) this;
        }

        public Criteria andTeamResourceDescIn(List<String> values) {
            addCriterion("TEAM_RESOURCE_DESC in", values, "teamResourceDesc");
            return (Criteria) this;
        }

        public Criteria andTeamResourceDescNotIn(List<String> values) {
            addCriterion("TEAM_RESOURCE_DESC not in", values, "teamResourceDesc");
            return (Criteria) this;
        }

        public Criteria andTeamResourceDescBetween(String value1, String value2) {
            addCriterion("TEAM_RESOURCE_DESC between", value1, value2, "teamResourceDesc");
            return (Criteria) this;
        }

        public Criteria andTeamResourceDescNotBetween(String value1, String value2) {
            addCriterion("TEAM_RESOURCE_DESC not between", value1, value2, "teamResourceDesc");
            return (Criteria) this;
        }

        public Criteria andTeamBelongToIsNull() {
            addCriterion("TEAM_BELONG_TO is null");
            return (Criteria) this;
        }

        public Criteria andTeamBelongToIsNotNull() {
            addCriterion("TEAM_BELONG_TO is not null");
            return (Criteria) this;
        }

        public Criteria andTeamBelongToEqualTo(String value) {
            addCriterion("TEAM_BELONG_TO =", value, "teamBelongTo");
            return (Criteria) this;
        }

        public Criteria andTeamBelongToNotEqualTo(String value) {
            addCriterion("TEAM_BELONG_TO <>", value, "teamBelongTo");
            return (Criteria) this;
        }

        public Criteria andTeamBelongToGreaterThan(String value) {
            addCriterion("TEAM_BELONG_TO >", value, "teamBelongTo");
            return (Criteria) this;
        }

        public Criteria andTeamBelongToGreaterThanOrEqualTo(String value) {
            addCriterion("TEAM_BELONG_TO >=", value, "teamBelongTo");
            return (Criteria) this;
        }

        public Criteria andTeamBelongToLessThan(String value) {
            addCriterion("TEAM_BELONG_TO <", value, "teamBelongTo");
            return (Criteria) this;
        }

        public Criteria andTeamBelongToLessThanOrEqualTo(String value) {
            addCriterion("TEAM_BELONG_TO <=", value, "teamBelongTo");
            return (Criteria) this;
        }

        public Criteria andTeamBelongToLike(String value) {
            addCriterion("TEAM_BELONG_TO like", value, "teamBelongTo");
            return (Criteria) this;
        }

        public Criteria andTeamBelongToNotLike(String value) {
            addCriterion("TEAM_BELONG_TO not like", value, "teamBelongTo");
            return (Criteria) this;
        }

        public Criteria andTeamBelongToIn(List<String> values) {
            addCriterion("TEAM_BELONG_TO in", values, "teamBelongTo");
            return (Criteria) this;
        }

        public Criteria andTeamBelongToNotIn(List<String> values) {
            addCriterion("TEAM_BELONG_TO not in", values, "teamBelongTo");
            return (Criteria) this;
        }

        public Criteria andTeamBelongToBetween(String value1, String value2) {
            addCriterion("TEAM_BELONG_TO between", value1, value2, "teamBelongTo");
            return (Criteria) this;
        }

        public Criteria andTeamBelongToNotBetween(String value1, String value2) {
            addCriterion("TEAM_BELONG_TO not between", value1, value2, "teamBelongTo");
            return (Criteria) this;
        }

        public Criteria andAbilityBaseIsNull() {
            addCriterion("ABILITY_BASE is null");
            return (Criteria) this;
        }

        public Criteria andAbilityBaseIsNotNull() {
            addCriterion("ABILITY_BASE is not null");
            return (Criteria) this;
        }

        public Criteria andAbilityBaseEqualTo(String value) {
            addCriterion("ABILITY_BASE =", value, "abilityBase");
            return (Criteria) this;
        }

        public Criteria andAbilityBaseNotEqualTo(String value) {
            addCriterion("ABILITY_BASE <>", value, "abilityBase");
            return (Criteria) this;
        }

        public Criteria andAbilityBaseGreaterThan(String value) {
            addCriterion("ABILITY_BASE >", value, "abilityBase");
            return (Criteria) this;
        }

        public Criteria andAbilityBaseGreaterThanOrEqualTo(String value) {
            addCriterion("ABILITY_BASE >=", value, "abilityBase");
            return (Criteria) this;
        }

        public Criteria andAbilityBaseLessThan(String value) {
            addCriterion("ABILITY_BASE <", value, "abilityBase");
            return (Criteria) this;
        }

        public Criteria andAbilityBaseLessThanOrEqualTo(String value) {
            addCriterion("ABILITY_BASE <=", value, "abilityBase");
            return (Criteria) this;
        }

        public Criteria andAbilityBaseLike(String value) {
            addCriterion("ABILITY_BASE like", value, "abilityBase");
            return (Criteria) this;
        }

        public Criteria andAbilityBaseNotLike(String value) {
            addCriterion("ABILITY_BASE not like", value, "abilityBase");
            return (Criteria) this;
        }

        public Criteria andAbilityBaseIn(List<String> values) {
            addCriterion("ABILITY_BASE in", values, "abilityBase");
            return (Criteria) this;
        }

        public Criteria andAbilityBaseNotIn(List<String> values) {
            addCriterion("ABILITY_BASE not in", values, "abilityBase");
            return (Criteria) this;
        }

        public Criteria andAbilityBaseBetween(String value1, String value2) {
            addCriterion("ABILITY_BASE between", value1, value2, "abilityBase");
            return (Criteria) this;
        }

        public Criteria andAbilityBaseNotBetween(String value1, String value2) {
            addCriterion("ABILITY_BASE not between", value1, value2, "abilityBase");
            return (Criteria) this;
        }

        public Criteria andOtherResourceIsNull() {
            addCriterion("OTHER_RESOURCE is null");
            return (Criteria) this;
        }

        public Criteria andOtherResourceIsNotNull() {
            addCriterion("OTHER_RESOURCE is not null");
            return (Criteria) this;
        }

        public Criteria andOtherResourceEqualTo(String value) {
            addCriterion("OTHER_RESOURCE =", value, "otherResource");
            return (Criteria) this;
        }

        public Criteria andOtherResourceNotEqualTo(String value) {
            addCriterion("OTHER_RESOURCE <>", value, "otherResource");
            return (Criteria) this;
        }

        public Criteria andOtherResourceGreaterThan(String value) {
            addCriterion("OTHER_RESOURCE >", value, "otherResource");
            return (Criteria) this;
        }

        public Criteria andOtherResourceGreaterThanOrEqualTo(String value) {
            addCriterion("OTHER_RESOURCE >=", value, "otherResource");
            return (Criteria) this;
        }

        public Criteria andOtherResourceLessThan(String value) {
            addCriterion("OTHER_RESOURCE <", value, "otherResource");
            return (Criteria) this;
        }

        public Criteria andOtherResourceLessThanOrEqualTo(String value) {
            addCriterion("OTHER_RESOURCE <=", value, "otherResource");
            return (Criteria) this;
        }

        public Criteria andOtherResourceLike(String value) {
            addCriterion("OTHER_RESOURCE like", value, "otherResource");
            return (Criteria) this;
        }

        public Criteria andOtherResourceNotLike(String value) {
            addCriterion("OTHER_RESOURCE not like", value, "otherResource");
            return (Criteria) this;
        }

        public Criteria andOtherResourceIn(List<String> values) {
            addCriterion("OTHER_RESOURCE in", values, "otherResource");
            return (Criteria) this;
        }

        public Criteria andOtherResourceNotIn(List<String> values) {
            addCriterion("OTHER_RESOURCE not in", values, "otherResource");
            return (Criteria) this;
        }

        public Criteria andOtherResourceBetween(String value1, String value2) {
            addCriterion("OTHER_RESOURCE between", value1, value2, "otherResource");
            return (Criteria) this;
        }

        public Criteria andOtherResourceNotBetween(String value1, String value2) {
            addCriterion("OTHER_RESOURCE not between", value1, value2, "otherResource");
            return (Criteria) this;
        }

        public Criteria andSharingConditionIsNull() {
            addCriterion("SHARING_CONDITION is null");
            return (Criteria) this;
        }

        public Criteria andSharingConditionIsNotNull() {
            addCriterion("SHARING_CONDITION is not null");
            return (Criteria) this;
        }

        public Criteria andSharingConditionEqualTo(String value) {
            addCriterion("SHARING_CONDITION =", value, "sharingCondition");
            return (Criteria) this;
        }

        public Criteria andSharingConditionNotEqualTo(String value) {
            addCriterion("SHARING_CONDITION <>", value, "sharingCondition");
            return (Criteria) this;
        }

        public Criteria andSharingConditionGreaterThan(String value) {
            addCriterion("SHARING_CONDITION >", value, "sharingCondition");
            return (Criteria) this;
        }

        public Criteria andSharingConditionGreaterThanOrEqualTo(String value) {
            addCriterion("SHARING_CONDITION >=", value, "sharingCondition");
            return (Criteria) this;
        }

        public Criteria andSharingConditionLessThan(String value) {
            addCriterion("SHARING_CONDITION <", value, "sharingCondition");
            return (Criteria) this;
        }

        public Criteria andSharingConditionLessThanOrEqualTo(String value) {
            addCriterion("SHARING_CONDITION <=", value, "sharingCondition");
            return (Criteria) this;
        }

        public Criteria andSharingConditionLike(String value) {
            addCriterion("SHARING_CONDITION like", value, "sharingCondition");
            return (Criteria) this;
        }

        public Criteria andSharingConditionNotLike(String value) {
            addCriterion("SHARING_CONDITION not like", value, "sharingCondition");
            return (Criteria) this;
        }

        public Criteria andSharingConditionIn(List<String> values) {
            addCriterion("SHARING_CONDITION in", values, "sharingCondition");
            return (Criteria) this;
        }

        public Criteria andSharingConditionNotIn(List<String> values) {
            addCriterion("SHARING_CONDITION not in", values, "sharingCondition");
            return (Criteria) this;
        }

        public Criteria andSharingConditionBetween(String value1, String value2) {
            addCriterion("SHARING_CONDITION between", value1, value2, "sharingCondition");
            return (Criteria) this;
        }

        public Criteria andSharingConditionNotBetween(String value1, String value2) {
            addCriterion("SHARING_CONDITION not between", value1, value2, "sharingCondition");
            return (Criteria) this;
        }

        public Criteria andCostEstimateIsNull() {
            addCriterion("COST_ESTIMATE is null");
            return (Criteria) this;
        }

        public Criteria andCostEstimateIsNotNull() {
            addCriterion("COST_ESTIMATE is not null");
            return (Criteria) this;
        }

        public Criteria andCostEstimateEqualTo(String value) {
            addCriterion("COST_ESTIMATE =", value, "costEstimate");
            return (Criteria) this;
        }

        public Criteria andCostEstimateNotEqualTo(String value) {
            addCriterion("COST_ESTIMATE <>", value, "costEstimate");
            return (Criteria) this;
        }

        public Criteria andCostEstimateGreaterThan(String value) {
            addCriterion("COST_ESTIMATE >", value, "costEstimate");
            return (Criteria) this;
        }

        public Criteria andCostEstimateGreaterThanOrEqualTo(String value) {
            addCriterion("COST_ESTIMATE >=", value, "costEstimate");
            return (Criteria) this;
        }

        public Criteria andCostEstimateLessThan(String value) {
            addCriterion("COST_ESTIMATE <", value, "costEstimate");
            return (Criteria) this;
        }

        public Criteria andCostEstimateLessThanOrEqualTo(String value) {
            addCriterion("COST_ESTIMATE <=", value, "costEstimate");
            return (Criteria) this;
        }

        public Criteria andCostEstimateLike(String value) {
            addCriterion("COST_ESTIMATE like", value, "costEstimate");
            return (Criteria) this;
        }

        public Criteria andCostEstimateNotLike(String value) {
            addCriterion("COST_ESTIMATE not like", value, "costEstimate");
            return (Criteria) this;
        }

        public Criteria andCostEstimateIn(List<String> values) {
            addCriterion("COST_ESTIMATE in", values, "costEstimate");
            return (Criteria) this;
        }

        public Criteria andCostEstimateNotIn(List<String> values) {
            addCriterion("COST_ESTIMATE not in", values, "costEstimate");
            return (Criteria) this;
        }

        public Criteria andCostEstimateBetween(String value1, String value2) {
            addCriterion("COST_ESTIMATE between", value1, value2, "costEstimate");
            return (Criteria) this;
        }

        public Criteria andCostEstimateNotBetween(String value1, String value2) {
            addCriterion("COST_ESTIMATE not between", value1, value2, "costEstimate");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andJoinTimeIsNull() {
            addCriterion("JOIN_TIME is null");
            return (Criteria) this;
        }

        public Criteria andJoinTimeIsNotNull() {
            addCriterion("JOIN_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andJoinTimeEqualTo(Date value) {
            addCriterionForJDBCDate("JOIN_TIME =", value, "joinTime");
            return (Criteria) this;
        }

        public Criteria andJoinTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("JOIN_TIME <>", value, "joinTime");
            return (Criteria) this;
        }

        public Criteria andJoinTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("JOIN_TIME >", value, "joinTime");
            return (Criteria) this;
        }

        public Criteria andJoinTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("JOIN_TIME >=", value, "joinTime");
            return (Criteria) this;
        }

        public Criteria andJoinTimeLessThan(Date value) {
            addCriterionForJDBCDate("JOIN_TIME <", value, "joinTime");
            return (Criteria) this;
        }

        public Criteria andJoinTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("JOIN_TIME <=", value, "joinTime");
            return (Criteria) this;
        }

        public Criteria andJoinTimeIn(List<Date> values) {
            addCriterionForJDBCDate("JOIN_TIME in", values, "joinTime");
            return (Criteria) this;
        }

        public Criteria andJoinTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("JOIN_TIME not in", values, "joinTime");
            return (Criteria) this;
        }

        public Criteria andJoinTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("JOIN_TIME between", value1, value2, "joinTime");
            return (Criteria) this;
        }

        public Criteria andJoinTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("JOIN_TIME not between", value1, value2, "joinTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the trash table spp_sres
     *
     * @mbg.generated do_not_delete_during_merge Sat Oct 05 10:08:15 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the trash table spp_sres
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}