package com.plateform.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Tech implements EncodableEntity {

    private Integer id;
    private String abilityNo;
    private String memberNo;
    private String abilityDescription;
    private String abilityCategory;
    private String proDirection;
    private String principle;
    private String achivement;
    private String applyingArea;
    private String coopIntention;
    private String restriction;
    private String costEstimate;
    private String remark;
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    private Date submitTime;
    private Integer serviceTime;
    private Integer serviceSuccessTime;
    private String gradeEvaluation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column tech.ID
     *
     * @return the value of tech.ID
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column tech.ID
     *
     * @param id the value for tech.ID
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column tech.ABILITY_NO
     *
     * @return the value of tech.ABILITY_NO
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getAbilityNo() {
        return abilityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column tech.ABILITY_NO
     *
     * @param abilityNo the value for tech.ABILITY_NO
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setAbilityNo(String abilityNo) {
        this.abilityNo = abilityNo == null ? null : abilityNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column tech.MEMBER_NO
     *
     * @return the value of tech.MEMBER_NO
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getMemberNo() {
        return memberNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column tech.MEMBER_NO
     *
     * @param memberNo the value for tech.MEMBER_NO
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setMemberNo(String memberNo) {
        this.memberNo = memberNo == null ? null : memberNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column tech.ABILITY_DESCRIPTION
     *
     * @return the value of tech.ABILITY_DESCRIPTION
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getAbilityDescription() {
        return abilityDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column tech.ABILITY_DESCRIPTION
     *
     * @param abilityDescription the value for tech.ABILITY_DESCRIPTION
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setAbilityDescription(String abilityDescription) {
        this.abilityDescription = abilityDescription == null ? null : abilityDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column tech.ABILITY_CATEGORY
     *
     * @return the value of tech.ABILITY_CATEGORY
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getAbilityCategory() {
        return abilityCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column tech.ABILITY_CATEGORY
     *
     * @param abilityCategory the value for tech.ABILITY_CATEGORY
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setAbilityCategory(String abilityCategory) {
        this.abilityCategory = abilityCategory == null ? null : abilityCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column tech.PRO_DIRECTION
     *
     * @return the value of tech.PRO_DIRECTION
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getProDirection() {
        return proDirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column tech.PRO_DIRECTION
     *
     * @param proDirection the value for tech.PRO_DIRECTION
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setProDirection(String proDirection) {
        this.proDirection = proDirection == null ? null : proDirection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column tech.PRINCIPLE
     *
     * @return the value of tech.PRINCIPLE
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getPrinciple() {
        return principle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column tech.PRINCIPLE
     *
     * @param principle the value for tech.PRINCIPLE
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setPrinciple(String principle) {
        this.principle = principle == null ? null : principle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column tech.ACHIVEMENT
     *
     * @return the value of tech.ACHIVEMENT
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getAchivement() {
        return achivement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column tech.ACHIVEMENT
     *
     * @param achivement the value for tech.ACHIVEMENT
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setAchivement(String achivement) {
        this.achivement = achivement == null ? null : achivement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column tech.APPLYING_AREA
     *
     * @return the value of tech.APPLYING_AREA
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getApplyingArea() {
        return applyingArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column tech.APPLYING_AREA
     *
     * @param applyingArea the value for tech.APPLYING_AREA
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setApplyingArea(String applyingArea) {
        this.applyingArea = applyingArea == null ? null : applyingArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column tech.COOP_INTENTION
     *
     * @return the value of tech.COOP_INTENTION
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getCoopIntention() {
        return coopIntention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column tech.COOP_INTENTION
     *
     * @param coopIntention the value for tech.COOP_INTENTION
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setCoopIntention(String coopIntention) {
        this.coopIntention = coopIntention == null ? null : coopIntention.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column tech.RESTRICTION
     *
     * @return the value of tech.RESTRICTION
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getRestriction() {
        return restriction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column tech.RESTRICTION
     *
     * @param restriction the value for tech.RESTRICTION
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setRestriction(String restriction) {
        this.restriction = restriction == null ? null : restriction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column tech.COST_ESTIMATE
     *
     * @return the value of tech.COST_ESTIMATE
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getCostEstimate() {
        return costEstimate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column tech.COST_ESTIMATE
     *
     * @param costEstimate the value for tech.COST_ESTIMATE
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setCostEstimate(String costEstimate) {
        this.costEstimate = costEstimate == null ? null : costEstimate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column tech.REMARK
     *
     * @return the value of tech.REMARK
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column tech.REMARK
     *
     * @param remark the value for tech.REMARK
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column tech.SUBMIT_TIME
     *
     * @return the value of tech.SUBMIT_TIME
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public Date getSubmitTime() {
        return submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column tech.SUBMIT_TIME
     *
     * @param submitTime the value for tech.SUBMIT_TIME
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setSubmitTime(Date submitTime) {
        this.submitTime = submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column tech.SERVICE_TIME
     *
     * @return the value of tech.SERVICE_TIME
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public Integer getServiceTime() {
        return serviceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column tech.SERVICE_TIME
     *
     * @param serviceTime the value for tech.SERVICE_TIME
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setServiceTime(Integer serviceTime) {
        this.serviceTime = serviceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column tech.SERVICE_SUCCESS_TIME
     *
     * @return the value of tech.SERVICE_SUCCESS_TIME
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public Integer getServiceSuccessTime() {
        return serviceSuccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column tech.SERVICE_SUCCESS_TIME
     *
     * @param serviceSuccessTime the value for tech.SERVICE_SUCCESS_TIME
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setServiceSuccessTime(Integer serviceSuccessTime) {
        this.serviceSuccessTime = serviceSuccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column tech.GRADE_EVALUATION
     *
     * @return the value of tech.GRADE_EVALUATION
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public String getGradeEvaluation() {
        return gradeEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column tech.GRADE_EVALUATION
     *
     * @param gradeEvaluation the value for tech.GRADE_EVALUATION
     *
     * @mbg.generated Sat Sep 21 11:34:28 CST 2019
     */
    public void setGradeEvaluation(String gradeEvaluation) {
        this.gradeEvaluation = gradeEvaluation == null ? null : gradeEvaluation.trim();
    }
}