package com.plateform.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TechExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the trash table spp_tech
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the trash table spp_tech
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the trash table spp_tech
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_tech
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    public TechExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_tech
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_tech
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_tech
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_tech
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_tech
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_tech
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_tech
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_tech
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_tech
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_tech
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the trash table spp_tech
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAbilityNoIsNull() {
            addCriterion("ABILITY_NO is null");
            return (Criteria) this;
        }

        public Criteria andAbilityNoIsNotNull() {
            addCriterion("ABILITY_NO is not null");
            return (Criteria) this;
        }

        public Criteria andAbilityNoEqualTo(String value) {
            addCriterion("ABILITY_NO =", value, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoNotEqualTo(String value) {
            addCriterion("ABILITY_NO <>", value, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoGreaterThan(String value) {
            addCriterion("ABILITY_NO >", value, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoGreaterThanOrEqualTo(String value) {
            addCriterion("ABILITY_NO >=", value, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoLessThan(String value) {
            addCriterion("ABILITY_NO <", value, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoLessThanOrEqualTo(String value) {
            addCriterion("ABILITY_NO <=", value, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoLike(String value) {
            addCriterion("ABILITY_NO like", value, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoNotLike(String value) {
            addCriterion("ABILITY_NO not like", value, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoIn(List<String> values) {
            addCriterion("ABILITY_NO in", values, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoNotIn(List<String> values) {
            addCriterion("ABILITY_NO not in", values, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoBetween(String value1, String value2) {
            addCriterion("ABILITY_NO between", value1, value2, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andAbilityNoNotBetween(String value1, String value2) {
            addCriterion("ABILITY_NO not between", value1, value2, "abilityNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoIsNull() {
            addCriterion("MEMBER_NO is null");
            return (Criteria) this;
        }

        public Criteria andMemberNoIsNotNull() {
            addCriterion("MEMBER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andMemberNoEqualTo(String value) {
            addCriterion("MEMBER_NO =", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoNotEqualTo(String value) {
            addCriterion("MEMBER_NO <>", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoGreaterThan(String value) {
            addCriterion("MEMBER_NO >", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoGreaterThanOrEqualTo(String value) {
            addCriterion("MEMBER_NO >=", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoLessThan(String value) {
            addCriterion("MEMBER_NO <", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoLessThanOrEqualTo(String value) {
            addCriterion("MEMBER_NO <=", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoLike(String value) {
            addCriterion("MEMBER_NO like", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoNotLike(String value) {
            addCriterion("MEMBER_NO not like", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoIn(List<String> values) {
            addCriterion("MEMBER_NO in", values, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoNotIn(List<String> values) {
            addCriterion("MEMBER_NO not in", values, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoBetween(String value1, String value2) {
            addCriterion("MEMBER_NO between", value1, value2, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoNotBetween(String value1, String value2) {
            addCriterion("MEMBER_NO not between", value1, value2, "memberNo");
            return (Criteria) this;
        }

        public Criteria andAbilityDescriptionIsNull() {
            addCriterion("ABILITY_DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andAbilityDescriptionIsNotNull() {
            addCriterion("ABILITY_DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andAbilityDescriptionEqualTo(String value) {
            addCriterion("ABILITY_DESCRIPTION =", value, "abilityDescription");
            return (Criteria) this;
        }

        public Criteria andAbilityDescriptionNotEqualTo(String value) {
            addCriterion("ABILITY_DESCRIPTION <>", value, "abilityDescription");
            return (Criteria) this;
        }

        public Criteria andAbilityDescriptionGreaterThan(String value) {
            addCriterion("ABILITY_DESCRIPTION >", value, "abilityDescription");
            return (Criteria) this;
        }

        public Criteria andAbilityDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("ABILITY_DESCRIPTION >=", value, "abilityDescription");
            return (Criteria) this;
        }

        public Criteria andAbilityDescriptionLessThan(String value) {
            addCriterion("ABILITY_DESCRIPTION <", value, "abilityDescription");
            return (Criteria) this;
        }

        public Criteria andAbilityDescriptionLessThanOrEqualTo(String value) {
            addCriterion("ABILITY_DESCRIPTION <=", value, "abilityDescription");
            return (Criteria) this;
        }

        public Criteria andAbilityDescriptionLike(String value) {
            addCriterion("ABILITY_DESCRIPTION like", value, "abilityDescription");
            return (Criteria) this;
        }

        public Criteria andAbilityDescriptionNotLike(String value) {
            addCriterion("ABILITY_DESCRIPTION not like", value, "abilityDescription");
            return (Criteria) this;
        }

        public Criteria andAbilityDescriptionIn(List<String> values) {
            addCriterion("ABILITY_DESCRIPTION in", values, "abilityDescription");
            return (Criteria) this;
        }

        public Criteria andAbilityDescriptionNotIn(List<String> values) {
            addCriterion("ABILITY_DESCRIPTION not in", values, "abilityDescription");
            return (Criteria) this;
        }

        public Criteria andAbilityDescriptionBetween(String value1, String value2) {
            addCriterion("ABILITY_DESCRIPTION between", value1, value2, "abilityDescription");
            return (Criteria) this;
        }

        public Criteria andAbilityDescriptionNotBetween(String value1, String value2) {
            addCriterion("ABILITY_DESCRIPTION not between", value1, value2, "abilityDescription");
            return (Criteria) this;
        }

        public Criteria andAbilityCategoryIsNull() {
            addCriterion("ABILITY_CATEGORY is null");
            return (Criteria) this;
        }

        public Criteria andAbilityCategoryIsNotNull() {
            addCriterion("ABILITY_CATEGORY is not null");
            return (Criteria) this;
        }

        public Criteria andAbilityCategoryEqualTo(String value) {
            addCriterion("ABILITY_CATEGORY =", value, "abilityCategory");
            return (Criteria) this;
        }

        public Criteria andAbilityCategoryNotEqualTo(String value) {
            addCriterion("ABILITY_CATEGORY <>", value, "abilityCategory");
            return (Criteria) this;
        }

        public Criteria andAbilityCategoryGreaterThan(String value) {
            addCriterion("ABILITY_CATEGORY >", value, "abilityCategory");
            return (Criteria) this;
        }

        public Criteria andAbilityCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("ABILITY_CATEGORY >=", value, "abilityCategory");
            return (Criteria) this;
        }

        public Criteria andAbilityCategoryLessThan(String value) {
            addCriterion("ABILITY_CATEGORY <", value, "abilityCategory");
            return (Criteria) this;
        }

        public Criteria andAbilityCategoryLessThanOrEqualTo(String value) {
            addCriterion("ABILITY_CATEGORY <=", value, "abilityCategory");
            return (Criteria) this;
        }

        public Criteria andAbilityCategoryLike(String value) {
            addCriterion("ABILITY_CATEGORY like", value, "abilityCategory");
            return (Criteria) this;
        }

        public Criteria andAbilityCategoryNotLike(String value) {
            addCriterion("ABILITY_CATEGORY not like", value, "abilityCategory");
            return (Criteria) this;
        }

        public Criteria andAbilityCategoryIn(List<String> values) {
            addCriterion("ABILITY_CATEGORY in", values, "abilityCategory");
            return (Criteria) this;
        }

        public Criteria andAbilityCategoryNotIn(List<String> values) {
            addCriterion("ABILITY_CATEGORY not in", values, "abilityCategory");
            return (Criteria) this;
        }

        public Criteria andAbilityCategoryBetween(String value1, String value2) {
            addCriterion("ABILITY_CATEGORY between", value1, value2, "abilityCategory");
            return (Criteria) this;
        }

        public Criteria andAbilityCategoryNotBetween(String value1, String value2) {
            addCriterion("ABILITY_CATEGORY not between", value1, value2, "abilityCategory");
            return (Criteria) this;
        }

        public Criteria andProDirectionIsNull() {
            addCriterion("PRO_DIRECTION is null");
            return (Criteria) this;
        }

        public Criteria andProDirectionIsNotNull() {
            addCriterion("PRO_DIRECTION is not null");
            return (Criteria) this;
        }

        public Criteria andProDirectionEqualTo(String value) {
            addCriterion("PRO_DIRECTION =", value, "proDirection");
            return (Criteria) this;
        }

        public Criteria andProDirectionNotEqualTo(String value) {
            addCriterion("PRO_DIRECTION <>", value, "proDirection");
            return (Criteria) this;
        }

        public Criteria andProDirectionGreaterThan(String value) {
            addCriterion("PRO_DIRECTION >", value, "proDirection");
            return (Criteria) this;
        }

        public Criteria andProDirectionGreaterThanOrEqualTo(String value) {
            addCriterion("PRO_DIRECTION >=", value, "proDirection");
            return (Criteria) this;
        }

        public Criteria andProDirectionLessThan(String value) {
            addCriterion("PRO_DIRECTION <", value, "proDirection");
            return (Criteria) this;
        }

        public Criteria andProDirectionLessThanOrEqualTo(String value) {
            addCriterion("PRO_DIRECTION <=", value, "proDirection");
            return (Criteria) this;
        }

        public Criteria andProDirectionLike(String value) {
            addCriterion("PRO_DIRECTION like", value, "proDirection");
            return (Criteria) this;
        }

        public Criteria andProDirectionNotLike(String value) {
            addCriterion("PRO_DIRECTION not like", value, "proDirection");
            return (Criteria) this;
        }

        public Criteria andProDirectionIn(List<String> values) {
            addCriterion("PRO_DIRECTION in", values, "proDirection");
            return (Criteria) this;
        }

        public Criteria andProDirectionNotIn(List<String> values) {
            addCriterion("PRO_DIRECTION not in", values, "proDirection");
            return (Criteria) this;
        }

        public Criteria andProDirectionBetween(String value1, String value2) {
            addCriterion("PRO_DIRECTION between", value1, value2, "proDirection");
            return (Criteria) this;
        }

        public Criteria andProDirectionNotBetween(String value1, String value2) {
            addCriterion("PRO_DIRECTION not between", value1, value2, "proDirection");
            return (Criteria) this;
        }

        public Criteria andPrincipleIsNull() {
            addCriterion("PRINCIPLE is null");
            return (Criteria) this;
        }

        public Criteria andPrincipleIsNotNull() {
            addCriterion("PRINCIPLE is not null");
            return (Criteria) this;
        }

        public Criteria andPrincipleEqualTo(String value) {
            addCriterion("PRINCIPLE =", value, "principle");
            return (Criteria) this;
        }

        public Criteria andPrincipleNotEqualTo(String value) {
            addCriterion("PRINCIPLE <>", value, "principle");
            return (Criteria) this;
        }

        public Criteria andPrincipleGreaterThan(String value) {
            addCriterion("PRINCIPLE >", value, "principle");
            return (Criteria) this;
        }

        public Criteria andPrincipleGreaterThanOrEqualTo(String value) {
            addCriterion("PRINCIPLE >=", value, "principle");
            return (Criteria) this;
        }

        public Criteria andPrincipleLessThan(String value) {
            addCriterion("PRINCIPLE <", value, "principle");
            return (Criteria) this;
        }

        public Criteria andPrincipleLessThanOrEqualTo(String value) {
            addCriterion("PRINCIPLE <=", value, "principle");
            return (Criteria) this;
        }

        public Criteria andPrincipleLike(String value) {
            addCriterion("PRINCIPLE like", value, "principle");
            return (Criteria) this;
        }

        public Criteria andPrincipleNotLike(String value) {
            addCriterion("PRINCIPLE not like", value, "principle");
            return (Criteria) this;
        }

        public Criteria andPrincipleIn(List<String> values) {
            addCriterion("PRINCIPLE in", values, "principle");
            return (Criteria) this;
        }

        public Criteria andPrincipleNotIn(List<String> values) {
            addCriterion("PRINCIPLE not in", values, "principle");
            return (Criteria) this;
        }

        public Criteria andPrincipleBetween(String value1, String value2) {
            addCriterion("PRINCIPLE between", value1, value2, "principle");
            return (Criteria) this;
        }

        public Criteria andPrincipleNotBetween(String value1, String value2) {
            addCriterion("PRINCIPLE not between", value1, value2, "principle");
            return (Criteria) this;
        }

        public Criteria andAchivementIsNull() {
            addCriterion("ACHIVEMENT is null");
            return (Criteria) this;
        }

        public Criteria andAchivementIsNotNull() {
            addCriterion("ACHIVEMENT is not null");
            return (Criteria) this;
        }

        public Criteria andAchivementEqualTo(String value) {
            addCriterion("ACHIVEMENT =", value, "achivement");
            return (Criteria) this;
        }

        public Criteria andAchivementNotEqualTo(String value) {
            addCriterion("ACHIVEMENT <>", value, "achivement");
            return (Criteria) this;
        }

        public Criteria andAchivementGreaterThan(String value) {
            addCriterion("ACHIVEMENT >", value, "achivement");
            return (Criteria) this;
        }

        public Criteria andAchivementGreaterThanOrEqualTo(String value) {
            addCriterion("ACHIVEMENT >=", value, "achivement");
            return (Criteria) this;
        }

        public Criteria andAchivementLessThan(String value) {
            addCriterion("ACHIVEMENT <", value, "achivement");
            return (Criteria) this;
        }

        public Criteria andAchivementLessThanOrEqualTo(String value) {
            addCriterion("ACHIVEMENT <=", value, "achivement");
            return (Criteria) this;
        }

        public Criteria andAchivementLike(String value) {
            addCriterion("ACHIVEMENT like", value, "achivement");
            return (Criteria) this;
        }

        public Criteria andAchivementNotLike(String value) {
            addCriterion("ACHIVEMENT not like", value, "achivement");
            return (Criteria) this;
        }

        public Criteria andAchivementIn(List<String> values) {
            addCriterion("ACHIVEMENT in", values, "achivement");
            return (Criteria) this;
        }

        public Criteria andAchivementNotIn(List<String> values) {
            addCriterion("ACHIVEMENT not in", values, "achivement");
            return (Criteria) this;
        }

        public Criteria andAchivementBetween(String value1, String value2) {
            addCriterion("ACHIVEMENT between", value1, value2, "achivement");
            return (Criteria) this;
        }

        public Criteria andAchivementNotBetween(String value1, String value2) {
            addCriterion("ACHIVEMENT not between", value1, value2, "achivement");
            return (Criteria) this;
        }

        public Criteria andApplyingAreaIsNull() {
            addCriterion("APPLYING_AREA is null");
            return (Criteria) this;
        }

        public Criteria andApplyingAreaIsNotNull() {
            addCriterion("APPLYING_AREA is not null");
            return (Criteria) this;
        }

        public Criteria andApplyingAreaEqualTo(String value) {
            addCriterion("APPLYING_AREA =", value, "applyingArea");
            return (Criteria) this;
        }

        public Criteria andApplyingAreaNotEqualTo(String value) {
            addCriterion("APPLYING_AREA <>", value, "applyingArea");
            return (Criteria) this;
        }

        public Criteria andApplyingAreaGreaterThan(String value) {
            addCriterion("APPLYING_AREA >", value, "applyingArea");
            return (Criteria) this;
        }

        public Criteria andApplyingAreaGreaterThanOrEqualTo(String value) {
            addCriterion("APPLYING_AREA >=", value, "applyingArea");
            return (Criteria) this;
        }

        public Criteria andApplyingAreaLessThan(String value) {
            addCriterion("APPLYING_AREA <", value, "applyingArea");
            return (Criteria) this;
        }

        public Criteria andApplyingAreaLessThanOrEqualTo(String value) {
            addCriterion("APPLYING_AREA <=", value, "applyingArea");
            return (Criteria) this;
        }

        public Criteria andApplyingAreaLike(String value) {
            addCriterion("APPLYING_AREA like", value, "applyingArea");
            return (Criteria) this;
        }

        public Criteria andApplyingAreaNotLike(String value) {
            addCriterion("APPLYING_AREA not like", value, "applyingArea");
            return (Criteria) this;
        }

        public Criteria andApplyingAreaIn(List<String> values) {
            addCriterion("APPLYING_AREA in", values, "applyingArea");
            return (Criteria) this;
        }

        public Criteria andApplyingAreaNotIn(List<String> values) {
            addCriterion("APPLYING_AREA not in", values, "applyingArea");
            return (Criteria) this;
        }

        public Criteria andApplyingAreaBetween(String value1, String value2) {
            addCriterion("APPLYING_AREA between", value1, value2, "applyingArea");
            return (Criteria) this;
        }

        public Criteria andApplyingAreaNotBetween(String value1, String value2) {
            addCriterion("APPLYING_AREA not between", value1, value2, "applyingArea");
            return (Criteria) this;
        }

        public Criteria andCoopIntentionIsNull() {
            addCriterion("COOP_INTENTION is null");
            return (Criteria) this;
        }

        public Criteria andCoopIntentionIsNotNull() {
            addCriterion("COOP_INTENTION is not null");
            return (Criteria) this;
        }

        public Criteria andCoopIntentionEqualTo(String value) {
            addCriterion("COOP_INTENTION =", value, "coopIntention");
            return (Criteria) this;
        }

        public Criteria andCoopIntentionNotEqualTo(String value) {
            addCriterion("COOP_INTENTION <>", value, "coopIntention");
            return (Criteria) this;
        }

        public Criteria andCoopIntentionGreaterThan(String value) {
            addCriterion("COOP_INTENTION >", value, "coopIntention");
            return (Criteria) this;
        }

        public Criteria andCoopIntentionGreaterThanOrEqualTo(String value) {
            addCriterion("COOP_INTENTION >=", value, "coopIntention");
            return (Criteria) this;
        }

        public Criteria andCoopIntentionLessThan(String value) {
            addCriterion("COOP_INTENTION <", value, "coopIntention");
            return (Criteria) this;
        }

        public Criteria andCoopIntentionLessThanOrEqualTo(String value) {
            addCriterion("COOP_INTENTION <=", value, "coopIntention");
            return (Criteria) this;
        }

        public Criteria andCoopIntentionLike(String value) {
            addCriterion("COOP_INTENTION like", value, "coopIntention");
            return (Criteria) this;
        }

        public Criteria andCoopIntentionNotLike(String value) {
            addCriterion("COOP_INTENTION not like", value, "coopIntention");
            return (Criteria) this;
        }

        public Criteria andCoopIntentionIn(List<String> values) {
            addCriterion("COOP_INTENTION in", values, "coopIntention");
            return (Criteria) this;
        }

        public Criteria andCoopIntentionNotIn(List<String> values) {
            addCriterion("COOP_INTENTION not in", values, "coopIntention");
            return (Criteria) this;
        }

        public Criteria andCoopIntentionBetween(String value1, String value2) {
            addCriterion("COOP_INTENTION between", value1, value2, "coopIntention");
            return (Criteria) this;
        }

        public Criteria andCoopIntentionNotBetween(String value1, String value2) {
            addCriterion("COOP_INTENTION not between", value1, value2, "coopIntention");
            return (Criteria) this;
        }

        public Criteria andRestrictionIsNull() {
            addCriterion("RESTRICTION is null");
            return (Criteria) this;
        }

        public Criteria andRestrictionIsNotNull() {
            addCriterion("RESTRICTION is not null");
            return (Criteria) this;
        }

        public Criteria andRestrictionEqualTo(String value) {
            addCriterion("RESTRICTION =", value, "restriction");
            return (Criteria) this;
        }

        public Criteria andRestrictionNotEqualTo(String value) {
            addCriterion("RESTRICTION <>", value, "restriction");
            return (Criteria) this;
        }

        public Criteria andRestrictionGreaterThan(String value) {
            addCriterion("RESTRICTION >", value, "restriction");
            return (Criteria) this;
        }

        public Criteria andRestrictionGreaterThanOrEqualTo(String value) {
            addCriterion("RESTRICTION >=", value, "restriction");
            return (Criteria) this;
        }

        public Criteria andRestrictionLessThan(String value) {
            addCriterion("RESTRICTION <", value, "restriction");
            return (Criteria) this;
        }

        public Criteria andRestrictionLessThanOrEqualTo(String value) {
            addCriterion("RESTRICTION <=", value, "restriction");
            return (Criteria) this;
        }

        public Criteria andRestrictionLike(String value) {
            addCriterion("RESTRICTION like", value, "restriction");
            return (Criteria) this;
        }

        public Criteria andRestrictionNotLike(String value) {
            addCriterion("RESTRICTION not like", value, "restriction");
            return (Criteria) this;
        }

        public Criteria andRestrictionIn(List<String> values) {
            addCriterion("RESTRICTION in", values, "restriction");
            return (Criteria) this;
        }

        public Criteria andRestrictionNotIn(List<String> values) {
            addCriterion("RESTRICTION not in", values, "restriction");
            return (Criteria) this;
        }

        public Criteria andRestrictionBetween(String value1, String value2) {
            addCriterion("RESTRICTION between", value1, value2, "restriction");
            return (Criteria) this;
        }

        public Criteria andRestrictionNotBetween(String value1, String value2) {
            addCriterion("RESTRICTION not between", value1, value2, "restriction");
            return (Criteria) this;
        }

        public Criteria andCostEstimateIsNull() {
            addCriterion("COST_ESTIMATE is null");
            return (Criteria) this;
        }

        public Criteria andCostEstimateIsNotNull() {
            addCriterion("COST_ESTIMATE is not null");
            return (Criteria) this;
        }

        public Criteria andCostEstimateEqualTo(String value) {
            addCriterion("COST_ESTIMATE =", value, "costEstimate");
            return (Criteria) this;
        }

        public Criteria andCostEstimateNotEqualTo(String value) {
            addCriterion("COST_ESTIMATE <>", value, "costEstimate");
            return (Criteria) this;
        }

        public Criteria andCostEstimateGreaterThan(String value) {
            addCriterion("COST_ESTIMATE >", value, "costEstimate");
            return (Criteria) this;
        }

        public Criteria andCostEstimateGreaterThanOrEqualTo(String value) {
            addCriterion("COST_ESTIMATE >=", value, "costEstimate");
            return (Criteria) this;
        }

        public Criteria andCostEstimateLessThan(String value) {
            addCriterion("COST_ESTIMATE <", value, "costEstimate");
            return (Criteria) this;
        }

        public Criteria andCostEstimateLessThanOrEqualTo(String value) {
            addCriterion("COST_ESTIMATE <=", value, "costEstimate");
            return (Criteria) this;
        }

        public Criteria andCostEstimateLike(String value) {
            addCriterion("COST_ESTIMATE like", value, "costEstimate");
            return (Criteria) this;
        }

        public Criteria andCostEstimateNotLike(String value) {
            addCriterion("COST_ESTIMATE not like", value, "costEstimate");
            return (Criteria) this;
        }

        public Criteria andCostEstimateIn(List<String> values) {
            addCriterion("COST_ESTIMATE in", values, "costEstimate");
            return (Criteria) this;
        }

        public Criteria andCostEstimateNotIn(List<String> values) {
            addCriterion("COST_ESTIMATE not in", values, "costEstimate");
            return (Criteria) this;
        }

        public Criteria andCostEstimateBetween(String value1, String value2) {
            addCriterion("COST_ESTIMATE between", value1, value2, "costEstimate");
            return (Criteria) this;
        }

        public Criteria andCostEstimateNotBetween(String value1, String value2) {
            addCriterion("COST_ESTIMATE not between", value1, value2, "costEstimate");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeIsNull() {
            addCriterion("SUBMIT_TIME is null");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeIsNotNull() {
            addCriterion("SUBMIT_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeEqualTo(Date value) {
            addCriterionForJDBCDate("SUBMIT_TIME =", value, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("SUBMIT_TIME <>", value, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("SUBMIT_TIME >", value, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SUBMIT_TIME >=", value, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeLessThan(Date value) {
            addCriterionForJDBCDate("SUBMIT_TIME <", value, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SUBMIT_TIME <=", value, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeIn(List<Date> values) {
            addCriterionForJDBCDate("SUBMIT_TIME in", values, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("SUBMIT_TIME not in", values, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SUBMIT_TIME between", value1, value2, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SUBMIT_TIME not between", value1, value2, "submitTime");
            return (Criteria) this;
        }

        public Criteria andServiceTimeIsNull() {
            addCriterion("SERVICE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andServiceTimeIsNotNull() {
            addCriterion("SERVICE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andServiceTimeEqualTo(Integer value) {
            addCriterion("SERVICE_TIME =", value, "serviceTime");
            return (Criteria) this;
        }

        public Criteria andServiceTimeNotEqualTo(Integer value) {
            addCriterion("SERVICE_TIME <>", value, "serviceTime");
            return (Criteria) this;
        }

        public Criteria andServiceTimeGreaterThan(Integer value) {
            addCriterion("SERVICE_TIME >", value, "serviceTime");
            return (Criteria) this;
        }

        public Criteria andServiceTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("SERVICE_TIME >=", value, "serviceTime");
            return (Criteria) this;
        }

        public Criteria andServiceTimeLessThan(Integer value) {
            addCriterion("SERVICE_TIME <", value, "serviceTime");
            return (Criteria) this;
        }

        public Criteria andServiceTimeLessThanOrEqualTo(Integer value) {
            addCriterion("SERVICE_TIME <=", value, "serviceTime");
            return (Criteria) this;
        }

        public Criteria andServiceTimeIn(List<Integer> values) {
            addCriterion("SERVICE_TIME in", values, "serviceTime");
            return (Criteria) this;
        }

        public Criteria andServiceTimeNotIn(List<Integer> values) {
            addCriterion("SERVICE_TIME not in", values, "serviceTime");
            return (Criteria) this;
        }

        public Criteria andServiceTimeBetween(Integer value1, Integer value2) {
            addCriterion("SERVICE_TIME between", value1, value2, "serviceTime");
            return (Criteria) this;
        }

        public Criteria andServiceTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("SERVICE_TIME not between", value1, value2, "serviceTime");
            return (Criteria) this;
        }

        public Criteria andServiceSuccessTimeIsNull() {
            addCriterion("SERVICE_SUCCESS_TIME is null");
            return (Criteria) this;
        }

        public Criteria andServiceSuccessTimeIsNotNull() {
            addCriterion("SERVICE_SUCCESS_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andServiceSuccessTimeEqualTo(Integer value) {
            addCriterion("SERVICE_SUCCESS_TIME =", value, "serviceSuccessTime");
            return (Criteria) this;
        }

        public Criteria andServiceSuccessTimeNotEqualTo(Integer value) {
            addCriterion("SERVICE_SUCCESS_TIME <>", value, "serviceSuccessTime");
            return (Criteria) this;
        }

        public Criteria andServiceSuccessTimeGreaterThan(Integer value) {
            addCriterion("SERVICE_SUCCESS_TIME >", value, "serviceSuccessTime");
            return (Criteria) this;
        }

        public Criteria andServiceSuccessTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("SERVICE_SUCCESS_TIME >=", value, "serviceSuccessTime");
            return (Criteria) this;
        }

        public Criteria andServiceSuccessTimeLessThan(Integer value) {
            addCriterion("SERVICE_SUCCESS_TIME <", value, "serviceSuccessTime");
            return (Criteria) this;
        }

        public Criteria andServiceSuccessTimeLessThanOrEqualTo(Integer value) {
            addCriterion("SERVICE_SUCCESS_TIME <=", value, "serviceSuccessTime");
            return (Criteria) this;
        }

        public Criteria andServiceSuccessTimeIn(List<Integer> values) {
            addCriterion("SERVICE_SUCCESS_TIME in", values, "serviceSuccessTime");
            return (Criteria) this;
        }

        public Criteria andServiceSuccessTimeNotIn(List<Integer> values) {
            addCriterion("SERVICE_SUCCESS_TIME not in", values, "serviceSuccessTime");
            return (Criteria) this;
        }

        public Criteria andServiceSuccessTimeBetween(Integer value1, Integer value2) {
            addCriterion("SERVICE_SUCCESS_TIME between", value1, value2, "serviceSuccessTime");
            return (Criteria) this;
        }

        public Criteria andServiceSuccessTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("SERVICE_SUCCESS_TIME not between", value1, value2, "serviceSuccessTime");
            return (Criteria) this;
        }

        public Criteria andGradeEvaluationIsNull() {
            addCriterion("GRADE_EVALUATION is null");
            return (Criteria) this;
        }

        public Criteria andGradeEvaluationIsNotNull() {
            addCriterion("GRADE_EVALUATION is not null");
            return (Criteria) this;
        }

        public Criteria andGradeEvaluationEqualTo(String value) {
            addCriterion("GRADE_EVALUATION =", value, "gradeEvaluation");
            return (Criteria) this;
        }

        public Criteria andGradeEvaluationNotEqualTo(String value) {
            addCriterion("GRADE_EVALUATION <>", value, "gradeEvaluation");
            return (Criteria) this;
        }

        public Criteria andGradeEvaluationGreaterThan(String value) {
            addCriterion("GRADE_EVALUATION >", value, "gradeEvaluation");
            return (Criteria) this;
        }

        public Criteria andGradeEvaluationGreaterThanOrEqualTo(String value) {
            addCriterion("GRADE_EVALUATION >=", value, "gradeEvaluation");
            return (Criteria) this;
        }

        public Criteria andGradeEvaluationLessThan(String value) {
            addCriterion("GRADE_EVALUATION <", value, "gradeEvaluation");
            return (Criteria) this;
        }

        public Criteria andGradeEvaluationLessThanOrEqualTo(String value) {
            addCriterion("GRADE_EVALUATION <=", value, "gradeEvaluation");
            return (Criteria) this;
        }

        public Criteria andGradeEvaluationLike(String value) {
            addCriterion("GRADE_EVALUATION like", value, "gradeEvaluation");
            return (Criteria) this;
        }

        public Criteria andGradeEvaluationNotLike(String value) {
            addCriterion("GRADE_EVALUATION not like", value, "gradeEvaluation");
            return (Criteria) this;
        }

        public Criteria andGradeEvaluationIn(List<String> values) {
            addCriterion("GRADE_EVALUATION in", values, "gradeEvaluation");
            return (Criteria) this;
        }

        public Criteria andGradeEvaluationNotIn(List<String> values) {
            addCriterion("GRADE_EVALUATION not in", values, "gradeEvaluation");
            return (Criteria) this;
        }

        public Criteria andGradeEvaluationBetween(String value1, String value2) {
            addCriterion("GRADE_EVALUATION between", value1, value2, "gradeEvaluation");
            return (Criteria) this;
        }

        public Criteria andGradeEvaluationNotBetween(String value1, String value2) {
            addCriterion("GRADE_EVALUATION not between", value1, value2, "gradeEvaluation");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the trash table spp_tech
     *
     * @mbg.generated do_not_delete_during_merge Sat Oct 05 10:08:15 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the trash table spp_tech
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}