package com.plateform.entity;

import java.util.Date;

public class Trans {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the trash column spt_trans.ID
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the trash column spt_trans.TRANS_TYPE
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    private String transType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the trash column spt_trans.APPLICANT_NO
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    private String applicantNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the trash column spt_trans.APPLY_TIME
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    private Date applyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the trash column spt_trans.HANDLER_ID
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    private String handlerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the trash column spt_trans.HANDLE_TIME
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    private Date handleTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the trash column spt_trans.TRANS_OBJID
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    private String transObjid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the trash column spt_trans.TRANS_STATUS
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    private String transStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the trash column spt_trans.REMARK
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_trans.ID
     *
     * @return the value of spt_trans.ID
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_trans.ID
     *
     * @param id the value for spt_trans.ID
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_trans.TRANS_TYPE
     *
     * @return the value of spt_trans.TRANS_TYPE
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    public String getTransType() {
        return transType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_trans.TRANS_TYPE
     *
     * @param transType the value for spt_trans.TRANS_TYPE
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    public void setTransType(String transType) {
        this.transType = transType == null ? null : transType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_trans.APPLICANT_NO
     *
     * @return the value of spt_trans.APPLICANT_NO
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    public String getApplicantNo() {
        return applicantNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_trans.APPLICANT_NO
     *
     * @param applicantNo the value for spt_trans.APPLICANT_NO
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    public void setApplicantNo(String applicantNo) {
        this.applicantNo = applicantNo == null ? null : applicantNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_trans.APPLY_TIME
     *
     * @return the value of spt_trans.APPLY_TIME
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_trans.APPLY_TIME
     *
     * @param applyTime the value for spt_trans.APPLY_TIME
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_trans.HANDLER_ID
     *
     * @return the value of spt_trans.HANDLER_ID
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    public String getHandlerId() {
        return handlerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_trans.HANDLER_ID
     *
     * @param handlerId the value for spt_trans.HANDLER_ID
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    public void setHandlerId(String handlerId) {
        this.handlerId = handlerId == null ? null : handlerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_trans.HANDLE_TIME
     *
     * @return the value of spt_trans.HANDLE_TIME
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    public Date getHandleTime() {
        return handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_trans.HANDLE_TIME
     *
     * @param handleTime the value for spt_trans.HANDLE_TIME
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    public void setHandleTime(Date handleTime) {
        this.handleTime = handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_trans.TRANS_OBJID
     *
     * @return the value of spt_trans.TRANS_OBJID
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    public String getTransObjid() {
        return transObjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_trans.TRANS_OBJID
     *
     * @param transObjid the value for spt_trans.TRANS_OBJID
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    public void setTransObjid(String transObjid) {
        this.transObjid = transObjid == null ? null : transObjid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_trans.TRANS_STATUS
     *
     * @return the value of spt_trans.TRANS_STATUS
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    public String getTransStatus() {
        return transStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_trans.TRANS_STATUS
     *
     * @param transStatus the value for spt_trans.TRANS_STATUS
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    public void setTransStatus(String transStatus) {
        this.transStatus = transStatus == null ? null : transStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the trash column spt_trans.REMARK
     *
     * @return the value of spt_trans.REMARK
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the trash column spt_trans.REMARK
     *
     * @param remark the value for spt_trans.REMARK
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }


    public Trans(String transType, String applicantNo, String transObjid, String transStatus) {
        this.id = null;
        this.applyTime = new Date();
        this.transType = transType;
        this.applicantNo = applicantNo;
        this.transObjid = transObjid;
        this.transStatus = transStatus;
    }


    public Trans() {

    }
}