package com.plateform.dao;

import java.util.List;

import com.plateform.entity.Demand;
import com.plateform.entity.DemandExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;

public interface DemandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spt_demand
     *
     * @mbg.generated Sun Oct 13 12:20:18 CST 2019
     */
    long countByExample(DemandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spt_demand
     *
     * @mbg.generated Sun Oct 13 12:20:18 CST 2019
     */
    int deleteByExample(DemandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spt_demand
     *
     * @mbg.generated Sun Oct 13 12:20:18 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spt_demand
     *
     * @mbg.generated Sun Oct 13 12:20:18 CST 2019
     */
    int insert(Demand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spt_demand
     *
     * @mbg.generated Sun Oct 13 12:20:18 CST 2019
     */
    int insertSelective(Demand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spt_demand
     *
     * @mbg.generated Sun Oct 13 12:20:18 CST 2019
     */
    List<Demand> selectByExample(DemandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spt_demand
     *
     * @mbg.generated Sun Oct 13 12:20:18 CST 2019
     */
    Demand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spt_demand
     *
     * @mbg.generated Sun Oct 13 12:20:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") Demand record, @Param("example") DemandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spt_demand
     *
     * @mbg.generated Sun Oct 13 12:20:18 CST 2019
     */
    int updateByExample(@Param("record") Demand record, @Param("example") DemandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spt_demand
     *
     * @mbg.generated Sun Oct 13 12:20:18 CST 2019
     */
    int updateByPrimaryKeySelective(Demand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spt_demand
     *
     * @mbg.generated Sun Oct 13 12:20:18 CST 2019
     */
    int updateByPrimaryKey(Demand record);


    @Delete("delete from spt_demand")
    void deleteAll();

    @Update("alter table spt_demand auto_increment=1")
    void alterId();
}