package com.plateform.dao;

import com.plateform.entity.Tech;
import com.plateform.entity.TechExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TechMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_tech
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    long countByExample(TechExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_tech
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    int deleteByExample(TechExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_tech
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_tech
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    int insert(Tech record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_tech
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    int insertSelective(Tech record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_tech
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    List<Tech> selectByExample(TechExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_tech
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    Tech selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_tech
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") Tech record, @Param("example") TechExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_tech
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    int updateByExample(@Param("record") Tech record, @Param("example") TechExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_tech
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    int updateByPrimaryKeySelective(Tech record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_tech
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    int updateByPrimaryKey(Tech record);
}