package com.plateform.dao;

import com.plateform.entity.Sres;
import com.plateform.entity.SresExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TempSresMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_sres
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    long countByExample(SresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_sres
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    int deleteByExample(SresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_sres
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_sres
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    int insert(Sres record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_sres
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    int insertSelective(Sres record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_sres
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    List<Sres> selectByExample(SresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_sres
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    Sres selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_sres
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") Sres record, @Param("example") SresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_sres
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    int updateByExample(@Param("record") Sres record, @Param("example") SresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_sres
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    int updateByPrimaryKeySelective(Sres record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spp_sres
     *
     * @mbg.generated Sat Oct 05 10:08:15 CST 2019
     */
    int updateByPrimaryKey(Sres record);
}