package com.plateform.dao;

import com.plateform.entity.Trans;
import com.plateform.entity.TransExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spt_trans
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    long countByExample(TransExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spt_trans
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    int deleteByExample(TransExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spt_trans
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spt_trans
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    int insert(Trans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spt_trans
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    int insertSelective(Trans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spt_trans
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    List<Trans> selectByExample(TransExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spt_trans
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    Trans selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spt_trans
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    int updateByExampleSelective(@Param("record") Trans record, @Param("example") TransExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spt_trans
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    int updateByExample(@Param("record") Trans record, @Param("example") TransExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spt_trans
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    int updateByPrimaryKeySelective(Trans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the trash table spt_trans
     *
     * @mbg.generated Mon Oct 07 18:29:21 CST 2019
     */
    int updateByPrimaryKey(Trans record);

    int updateMemberStatusByMemberNo(@Param("memberNo") String memberNo,@Param("memberStatus") String memberStatus);
}